mongodb-labs/drivers-evergreen-tools

.evergreen/run-orchestration.sh
We're seeing some weird failures where it looks like `mongo-orchestration stop` does not shutdown  MO:
```
[2017/02/27 12:08:25.844] + mongo-orchestration stop
[2017/02/27 12:08:26.264] ERROR: The process "2612" not found.
``` 
The next task to run on that machine may or may not work. Forcibly killing MO before starting it up should fix some failures.
Evergreen:https://evergreen.mongodb.com/version/58b4d5ed3ff1223783027a97
A patch that actually kills an existing MO instance:
https://evergreen.mongodb.com/task_log_raw/drivers_tools_tests_windows__os_windows~windows_64_vs2015_test_auth~noauth_ssl~nossl_test_3.2_sharded_cluster_4a1c22355e929daf80a641e6f1a4791a0255c231_17_02_27_23_27_11/0?type=T#L577
=> Kill MO on port 8889 incase it is left running

.evergreen/download-mongodb.sh, .evergreen/run-orchestration.sh
=> Update run-orchestration for nightlies

.evergreen/orchestration/configs/sharded_clusters/auth-ssl.json, .evergreen/orchestration/configs/sharded_clusters/auth.json, .evergreen/orchestration/configs/sharded_clusters/basic-ssl.json, .evergreen/orchestration/configs/sharded_clusters/basic.json
Resolves #24.
Evergreen: https://evergreen.mongodb.com/version/5a020a83e3c3316365000399
=> Start shards as three member replica sets.

.evergreen/config.yml, .evergreen/download-mongodb.sh
Patch: https://evergreen.mongodb.com/version/5a95f4532fbabe3c515f0564
=> Add Debian 9.2 support

.evergreen/orchestration/configs/sharded_clusters/auth-ssl.json, .evergreen/orchestration/configs/sharded_clusters/auth.json, .evergreen/orchestration/configs/sharded_clusters/basic-ssl.json, .evergreen/orchestration/configs/sharded_clusters/basic.json
Waiting for driver validation on [DRIVERS-592](https://jira.mongodb.org/browse/DRIVERS-592) to merge.
=> DRIVERS-592 Remove unused second shard

.evergreen/download-mongodb.sh
evergreen patch: https://evergreen.mongodb.com/version/5c1958c3c9ec44819f9476c6
=> use MongoDB 3.4.18

.evergreen/download-mongodb.sh, .evergreen/start-orchestration.sh
Tested with the python driver here: https://evergreen.mongodb.com/version/5c5ddd9d57e85a408057a3d4
=> Update to MongoDB 3.2.22, 3.4.19, 3.6.10, 4.0.6

.evergreen/orchestration/configs/replica_sets/disableTestCommands.json, .evergreen/orchestration/configs/servers/disableTestCommands.json, .evergreen/orchestration/configs/sharded_clusters/auth.json, .evergreen/orchestration/configs/sharded_clusters/basic-ssl.json, .evergreen/orchestration/configs/sharded_clusters/basic.json, .evergreen/orchestration/configs/sharded_clusters/disableTestCommands.json, .evergreen/run-orchestration.sh, .evergreen/start-orchestration.sh
Jira: https://jira.mongodb.org/browse/PYTHON-1773
Patch: https://evergreen.mongodb.com/version/5c8858bda4cf471e23b36d8d
=> PYTHON-1773 Add disableTestCommands cluster configs

.evergreen/download-mongodb.sh
Server is tagged and all the download links work
=> Update MONGODB_42 to 4.2.0

.evergreen/download-mongodb.sh
Update to the latest patch versions.
=> Update MongoDB 4.2.1

.evergreen/run-orchestration.sh
Not sure if this new behavior needs to be documented anywhere.
=> Accept custom configuration file in run-orchestration.sh

.evergreen/ocsp/mock-ocsp-responder-requirements.txt
https://evergreen.mongodb.com/version/5e7d108557e85a2a25d4a707
https://jira.mongodb.org/browse/DRIVERS-977
=> Add OCSP mock responder dependencies

.evergreen/download-mongodb.sh
=> Use v4.4-latest download for macOS

.evergreen/config.yml, .evergreen/start-orchestration.sh
Fixes: https://github.com/mongodb-labs/drivers-evergreen-tools/issues/43
=> Use Python 3 from the toolchain when available

.evergreen/ocsp/mock_ocsp_responder.py, .evergreen/ocsp/ocsp_mock.py
This is needed when running the mock in Docker
and using it from the host system.
=> Add --bind_ip argument to ocsp mock

.evergreen/atlas_data_lake/build-mongohouse-local.sh, .evergreen/atlas_data_lake/run-mongohouse-local.sh
A number of fixes for running mongohouse on windows.
C# Driver ticket: https://jira.mongodb.org/browse/CSHARP-3162
Evergreen: https://evergreen.mongodb.com/version/5f523f2a2fbabe01bfba5553
=> CSHARP-3162: Testing Data Lake with Drivers

.evergreen/csfle/print-temp-creds.py, .evergreen/csfle/set-temp-creds.sh
Includes scripts to obtain temporary AWS credentials for testing CSFLE.
=> SPEC-1774 add CSFLE temp credentials script

.evergreen/auth_aws/lib/ecs_hosted_test.js
Ongoing patch here: https://spruce.mongodb.com/version/618178bbe3c331705d6c70aa
=> DRIVERS-1971 Stop using runMongoProgram to run shell scripts

.evergreen/ocsp/mock-ocsp-responder-requirements.txt
Testing here: https://spruce.mongodb.com/version/62181aec2fbabe75de523b76/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> DRIVERS-2217 Upgrade mock OCSP responder deps

.evergreen/mongodl.py
For convenience. I would like to add mongodl.py to my PATH.
=> add shebang to mongodl.py

.evergreen/start-orchestration.sh
Workaround for this bug: https://github.com/bottlepy/bottle/issues/1377
=> Workaround bug in bottle 0.12.20

.evergreen/auth_aws/activate_venv.sh, .evergreen/csfle/activate_venv.sh, .evergreen/utils.sh
Testing here: https://spruce.mongodb.com/version/6298eb10c9ec447522cc39db/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> DRIVERS-2346 Upgrade pip/setuptools when using venv

.evergreen/download-mongodb.sh
We need these for Rust testing.
=> Add 6.0 download links for linux-ubuntu-18.04-aarch64

.evergreen/download-mongodb.sh, .evergreen/run-orchestration.sh
Related driver PR https://github.com/mongodb/mongo-csharp-driver/pull/860
=> CSHARP-4254: Test with consistent versions of crypt_shared and server. 

.evergreen/download-mongodb.sh
EG: https://evergreen.mongodb.com/version/638780470305b95f2fad7e92
=> Add darwin arm for rapid

.evergreen/serverless/create-instance.sh, .evergreen/serverless/delete-instance.sh, .evergreen/serverless/get-instance.sh
https://jira.mongodb.org/browse/DRIVERS-2519
=> DRIVERS-2519: Utilize find-python3.sh in create-serverless.sh

.evergreen/config.yml, .evergreen/install-dependencies.sh
Follow up to https://github.com/10gen/mongo-orchestration/pull/301
=> Update EG Matrix MongoDB 3.6+

.evergreen/auth_oidc/oidc_write_orchestration.py, .evergreen/auth_oidc/setup_oidc.js
cc @DmitryLukyanov 
Avoids error when the replica set has not yet been configured.
=> DRIVERS-2415 Ensure 27017 is the Primary in the OIDC Replica Set

.evergreen/download-mongodb.sh
Related to https://jira.mongodb.org/browse/DRIVERS-2592
=> Support RHEL 7.6

.evergreen/mongodl.py
PopOS is based on Ubuntu: https://pop.system76.com/
=> Add support for Pop Os

.evergreen/download-mongodb.sh
https://jira.mongodb.org/browse/DRIVERS-2625
=> DRIVERS-2625 Use curl --retry-all-errors when it's supported

.evergreen/atlas_data_lake/build-mongohouse-local.sh
=> DRIVERS-2636: bump adl go version

.evergreen/auth_oidc/azure/start-mongodb.sh
Use tools from master.
Fixes: https://evergreen.mongodb.com/task_log_raw/mongo_node_driver_next_ubuntu20_test_azure_oidc_oidc_auth_test_azure_latest_patch_8bfa945f0db911bf49ef3cabeda35e859ffc020a_6476373f1e2d17e8970a5f0c_23_05_30_17_49_52/0?type=T#L1019
=> test: fix missing branch DRIVERS-2416

.evergreen/auth_aws/activate-authawsvenv.sh, .evergreen/auth_aws/aws_tester.py, .evergreen/auth_aws/lib/aws_assume_role.py, .evergreen/auth_aws/lib/aws_assume_web_role.py
Tested with https://github.com/mongodb/mongo-python-driver/pull/1220, and with a patch build that uses this branch without changing any EG config.
=> DRIVERS-2328 Fix Windows Support for AWS Scripts

.evergreen/auth_oidc/oidc_get_tokens.py, .evergreen/auth_oidc/oidc_write_orchestration.py
=> DRIVERS-2415 More tokens and add requestScopes

.evergreen/download-mongodb.sh
- Use stable release branches to pick up patch releases automatically.
- Prune unsupported server versions and platforms.
=> Clean up download links

.evergreen/download-mongodb.sh
Reverts mongodb-labs/drivers-evergreen-tools#315
=> Revert "Clean up download links"

.evergreen/atlas_data_lake/config.yml
https://github.com/10gen/mongohouse/pull/6307
=> fix: mongohouse billing config restructure

.evergreen/atlas_data_lake/config.yml
=> NODE-5503: fix ADL config by adding dls section

.evergreen/auth_aws/setup_secrets.py
Testing in this [build](https://spruce.mongodb.com/task/mongo_python_driver_atlas_connect__platform~rhel8_python_version~pypy3.10_atlas_connect_patch_8029c180ebbb239480c2017ce256289349bae067_651b3dc07742ae579dec1b7d_23_10_02_22_01_43/logs?execution=0).
=> PYTHON-3942 Follow up - fix for unbound variable

.evergreen/download-mongodb.sh
This PR updates to the latest server versions.
=> Update download-mongodb.sh with latest server versions

.evergreen/auth_aws/aws_setup.sh, .evergreen/auth_aws/aws_tester.py, .evergreen/auth_aws/lib/aws_assume_role.py, .evergreen/auth_aws/lib/aws_assume_web_role.py, .evergreen/auth_aws/setup_secrets.sh, .gitignore
Tested with https://github.com/mongodb/mongo-go-driver/pull/1429 and https://github.com/mongodb/mongo-python-driver/pull/1397.
Passing [build](https://spruce.mongodb.com/version/652e63c7a4cf47c99a53a3bb/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC).
=> DRIVERS-2328 Add aws_setup convenience script

.evergreen/auth_aws/aws_tester.py
Testing with https://spruce.mongodb.com/version/65494367e3c3311933e4dd4f/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> DRIVERS-2747 Fix OS detection

.evergreen/run-orchestration.sh
Follow-Up to DRIVERS-2328. Also added documentation for the new environment variable.
=> Fix typo in legacy shell environment variable

.evergreen/config.yml
https://jira.mongodb.org/browse/DEVPROD-4324
=> DEVPROD-4324 Avoid logging secrets

.evergreen/github_app/README.md, .evergreen/github_app/apply-labels.mjs, .evergreen/github_app/apply-labels.sh, .evergreen/github_app/package-lock.json, .evergreen/github_app/package.json
Testing with https://github.com/mongodb/mongo-go-driver/pull/1569.
=> GODRIVER-3139 Automatically Add Labels to PRs

.evergreen/download-mongodb.sh
This updates to the latest patch versions for 7.0, 6.0, 5.0, and 4.4.
I've also slightly reorganised the version list to clarify what can and shouldn't be updated.
=> Update server versions

.evergreen/github_app/assign-reviewer.mjs, .evergreen/install-node.sh
Tested with https://github.com/mongodb/mongo-go-driver/pull/1572
=> GODRIVER-3148 Fix Node Install and Reviewer Assignment

.evergreen/auth_oidc/azure/README.md, .evergreen/auth_oidc/gcp/README.md, .evergreen/csfle/azurekms/README.md, .evergreen/csfle/gcpkms/README.md, .evergreen/docker/run-server.sh, .evergreen/secrets_handling/README.md, .evergreen/serverless/README.md, README.md
- Recommend the new `setup.sh` and `teardown.sh` scripts
- Improve the secrets handling docs
=> Documentation Improvements

.evergreen/auth_oidc/setup.sh, .evergreen/auth_oidc/start_local_server.sh, .evergreen/config.yml, .evergreen/docker/run-server.sh
Tested with https://github.com/mongodb/mongo-python-driver/pull/1556
=> DRIVERS-2836 Do not use Atlas on Linux OIDC tests

.evergreen/atlas/atlas-utils.sh, .evergreen/atlas/setup-atlas-cluster.sh, .evergreen/auth_oidc/azure/README.md, .evergreen/auth_oidc/azure/create-and-setup-vm.sh, .evergreen/auth_oidc/azure/handle_secrets.py, .evergreen/auth_oidc/azure/remote-scripts/test.py, .evergreen/auth_oidc/gcp/README.md, .evergreen/auth_oidc/oidc_write_orchestration.py
Tested with https://github.com/mongodb/mongo-python-driver/pull/1620
=> DRIVERS-2416 Clean up OIDC Variables

.evergreen/csfle/teardown.sh
Needed for https://github.com/mongodb/libmongocrypt/pull/836
=> Make CSFLE teardown more robust

.evergreen/k8s/configure-pod.sh
Avoid transient connection errors during pod startup.
=> Add retry on k8s pod configure

.evergreen/csfle/start-servers.sh
https://spruce.mongodb.com/version/66c8a50917703d00076c6f22/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> GODRIVER-3228 Allow overriding options for kms servers

.evergreen/github_app/apply-labels.sh
Bug seen in https://spruce.mongodb.com/task/mongo_go_driver_v1_pull_request_helpers_pull_request_helpers_patch_2e7cb372b05cba29facd58aac7e715c3cec4e377_66c778393d419d000791eac0_24_08_22_17_41_14/logs?execution=0 that was introduced in #470.
=>  DRIVERS-2956 Fix apply-labels script

.evergreen/atlas/atlas-utils.sh, .evergreen/auth_aws/activate-authawsvenv.sh, .evergreen/auth_oidc/activate-authoidcvenv.sh, .evergreen/csfle/activate-kmstlsvenv.sh, .evergreen/docker/ubuntu18.04/Dockerfile, .evergreen/docker/ubuntu20.04/Dockerfile, .evergreen/download-mongodb.sh, .evergreen/find-python3.sh, .evergreen/handle-paths.sh, .evergreen/ocsp/activate-ocspvenv.sh, .evergreen/run-orchestration.sh, .evergreen/serverless/create-instance.sh, .evergreen/start-orchestration.sh, .evergreen/stop-orchestration.sh, .gitignore, Makefile, README.md
Reverts mongodb-labs/drivers-evergreen-tools#473
=> Revert "Usability improvements"

.evergreen/atlas/setup.sh, .evergreen/csfle/azurekms/create-and-setup-vm.sh
Needed for https://github.com/mongodb/mongo-go-driver/pull/1776
=> GODRIVER-3311 Fix AzureKMS and Atlas Startup Scripts

.evergreen/start-orchestration.sh, .evergreen/stop-orchestration.sh
DRIVERS-2991 Prefer lsof over fuser for macos support.
=> DRIVERS-2991 Prefer lsof over fuser for macos support

.evergreen/download-mongodb.sh
DRIVERS-2994 Bump MongoDB version to 8.0.0
Also bump 5.0.29.
=> DRIVERS-2994 Bump MongoDB version to 8.0.0

.evergreen/download-mongodb.sh, .evergreen/mongodl.py, .github/workflows/tests.yml, scripts/update_mongodb_download.py
Reverts mongodb-labs/drivers-evergreen-tools#525
=> Revert "DRIVERS-3002 Use mongodl.py in download-mongodb.sh"

.evergreen/config.yml, .evergreen/mongosh-dl.py, .evergreen/tests/test-mongodl.sh
Redo of #540 with support for RHEL 8.0
=> DRIVERS-3030 Ensure mongosh download is properly working

.evergreen/csfle/start-servers.sh, .evergreen/csfle/stop-servers.sh, .evergreen/process-utils.sh, .evergreen/start-orchestration.sh
Patch build with node driver: https://spruce.mongodb.com/version/66fbf6d0f182430007cc5357/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> Clean up csfle server ports

.evergreen/csfle/await-servers.sh, .evergreen/csfle/start-servers.sh
DRIVERS-1541 Add kms_failpoint_server.py to start-servers.sh for KMS retry testing
=> DRIVERS-1541 Add kms_failpoint_server.py to start-servers.sh for KMS retry testing

.evergreen/csfle/gcpkms/download-gcloud.sh
Passing test: https://spruce.mongodb.com/task/drivers_tools_tests_oidc_test_oidc_gcp_patch_c7b7f52d23172b6a26b43730db9aea335ef8b6f9_674f947e5d190d0007e43fb0_24_12_03_23_30_17/logs?execution=0
=> DRIVERS-3062 Fix GCP OIDC Support

.evergreen/orchestration/drivers_orchestration.py
Passing C Build: https://spruce.mongodb.com/task/mongo_c_driver_sanitizers_matrix_asan_asan_cse_sasl_cyrus_openssl_ubuntu2004_clang_test_latest_server_auth_patch_45cf8937c533891e32eb595feee6538ad48b1e9e_679838103982530007b529a6_25_01_28_01_51_40/logs?execution=2
=> DRIVERS-3032 Fix handling of SSL variable

.evergreen/orchestration/drivers_orchestration.py
C Driver build: https://spruce.mongodb.com/version/67990f584b849100070ff26a/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> DRIVERS-3032 Fix handling of SSL env var

.evergreen/orchestration/drivers_orchestration.py
Fix error
> No such file or directory: ‘mo-expansion.yml’
=> DRIVERS-3032 Fix handling of skip_crypt_shared

.evergreen/config.yml, .evergreen/install-cli.sh
Reverts mongodb-labs/drivers-evergreen-tools#589
=> Revert "DRIVERS-3032 Add support for ubuntu2204-arm64"

.evergreen/orchestration/configs/servers/ecdsa-basic-tls-ocsp-disableStapling-singleEndpoint.json, .evergreen/orchestration/configs/servers/ecdsa-basic-tls-ocsp-disableStapling.json, .evergreen/orchestration/configs/servers/ecdsa-basic-tls-ocsp-mustStaple-disableStapling-singleEndpoint.json, .evergreen/orchestration/configs/servers/ecdsa-basic-tls-ocsp-mustStaple-disableStapling.json, .evergreen/orchestration/configs/servers/rsa-basic-tls-ocsp-disableStapling-singleEndpoint.json, .evergreen/orchestration/configs/servers/rsa-basic-tls-ocsp-disableStapling.json, .evergreen/orchestration/configs/servers/rsa-basic-tls-ocsp-mustStaple-disableStapling-singleEndpoint.json, .evergreen/orchestration/configs/servers/rsa-basic-tls-ocsp-mustStaple-disableStapling.json
Passing build in python: https://spruce.mongodb.com/version/67af34a75f7f3800079e69e2/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> DRIVERS-3032 Fix disableStapling

.evergreen/auth_oidc/oidc_get_tokens.sh, .evergreen/config.yml, .evergreen/csfle/stop-servers.sh, .evergreen/download-mongodb.sh, .evergreen/k8s/configure-pod.sh, .evergreen/process-utils.sh, .evergreen/run-orchestration.sh
- Remove remaining usages of xtrace
- Make task killing quieter
=> Make output quieter

.evergreen/auth_aws/aws_setup.sh, .evergreen/auth_aws/aws_tester.py, .evergreen/auth_aws/lib/aws_assign_instance_profile.py, .evergreen/orchestration/drivers_orchestration.py, .evergreen/run-orchestration.sh, .gitignore
Reverts mongodb-labs/drivers-evergreen-tools#619
=> Revert "PYTHON-5157 Convert aws tests to use python scripts"

.evergreen/auth_aws/activate-authawsvenv.sh, .evergreen/config.yml, .evergreen/find-python3.sh, .evergreen/install-cli.sh, .evergreen/setup.sh
Tested with a full C driver patch build.  Failures appear to be unrelated.
https://spruce.mongodb.com/version/67d1ad2f8ad854000773caeb/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> PYTHON-5203 Use uv from Python toolchain if available

.evergreen/atlas_data_lake/pull-mongohouse-image.sh, .evergreen/atlas_data_lake/run-mongohouse-image.sh, .evergreen/config.yml, .evergreen/docker/run-server.sh, .evergreen/docker/teardown.sh, .evergreen/orchestration/drivers_orchestration.py, .evergreen/run-orchestration.sh, .evergreen/teardown.sh, .github/workflows/tests.yml, .gitignore, Makefile, README.md, action.yml
C Driver regression check: https://spruce.mongodb.com/version/67e6ab4dc8878e0007f369aa/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC.  Darwin failures are due to [SERVER-103043](https://jira.mongodb.org/browse/SERVER-103043).
PyMongo test with local atlas: https://spruce.mongodb.com/version/67e6abee463ece0007c6dd16/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC.  Note that there are many test failures because we aren't fully set up to test a local atlas cluster - [PYTHON-5022](https://jira.mongodb.org/browse/PYTHON-5022).
=> DRIVERS-3055 Run atlas local cluster in Evergreen and GitHub actions

.evergreen/ocsp/mock_ocsp_responder.py, .evergreen/ocsp/ocsp_mock.py, .evergreen/ocsp/setup.sh
- Improve logging
- Add a check that the server is running
Required for https://github.com/mongodb/mongo-python-driver/pull/2254
=> PYTHON-5260 Clean up OCSP Server

.evergreen/orchestration/drivers_orchestration.py
Tested with https://spruce.mongodb.com/version/67f4051c439cc1000742c68c/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
It passed one two subsequent executions.
=> DRIVERS-3055 Fix podman setup

.evergreen/github_app/backport-pr.sh, .evergreen/github_app/setup-secrets.sh, .evergreen/github_app/utils.sh, .evergreen/tests/test-github-app.sh
Passing build: https://spruce.mongodb.com/version/68225989ef86ee00078be07b/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> Add ability to use release bot creds

.evergreen/perfcomp/README.md, .evergreen/perfcomp/cmd/perfcomp/mdreport.go
- PR comment toggle defaults to open
- Update README instructions for PR comment preview
=> DRIVERS-3254 Perfcomp Cleanup

.evergreen/orchestration/uv, .evergreen/orchestration/uvx, .gitignore
Follow up to #685 where I accidentally committed these files.  They are created locally due to #678.
=> Remove symlinked uv executables and add to gitignore
