mongodb-labs/drivers-evergreen-tools

- .evergreen/config.yml
With single quotes around the echo string, the expansion.yml file becomes:
```yml
DRIVERS_TOOLS: "$DRIVERS_TOOLS"
MONGO_ORCHESTRATION_HOME: "$MONGO_ORCHESTRATION_HOME"
MONGODB_BINARIES: "$MONGODB_BINARIES"
UPLOAD_BUCKET: "$UPLOAD_BUCKET"
PROJECT_DIRECTORY: "$PROJECT_DIRECTORY"
```
Without the quotes, the variables are expanded properly into:
```yml
DRIVERS_TOOLS: /Users/shane/git/drivers-evergreen-tools/../drivers-tools
MONGO_ORCHESTRATION_HOME: /Users/shane/git/drivers-evergreen-tools/../drivers-tools/.evergreen/orchestration
MONGODB_BINARIES: /Users/shane/git/drivers-evergreen-tools/../drivers-tools/mongodb/bin
UPLOAD_BUCKET: driver-tools
PROJECT_DIRECTORY: /Users/shane/git/drivers-evergreen-tools
```
> EVG-1331 Properly add variables to Evergreen expansions

- .evergreen/config.yml
- .evergreen/download-mongodb.sh
- .evergreen/run-orchestration.sh
Add links for Debian 7.1, Amazon x86_64 Linux, SLES 11, and SLES 12.
Also, changes MO setup to always install into a virtualenv where possible because mongo-orchestration doesn't run on Amazon x86_64 Linux otherwise.
> Add links for downloading MongoDB on more distros

- .evergreen/config.yml
- .evergreen/download-mongodb.sh
MongoDB 3.2 is available on Ubuntu 16.04 (x86_64).
> Add link for Ubuntu 16.04 (x86_64) MongoDB 3.2

- .evergreen/download-mongodb.sh
This will let drivers choose to test Linux x86_64 variants with all MongoDB versions (without SSL). For example, the Python driver wants to test all versions of Python against all version of the server on Ubuntu 16.04 (x86_64). When using the generic Linux builds for MongoDB 2.4, 2.6, and 3.0 we'll simply skip the SSL tests.
> Fallback to generic Linux x86_64 builds (without SSL) when no platform specific link is available

- .evergreen/config.yml
- .evergreen/stop-orchestration.sh
This splits stopping orchestration out of the `cleanup` function and puts
the actual work into a separate script.  This makes it more reusable by
Evergreen configs that don't exactly duplicate driver-tools.
Patch build is looking good: https://evergreen.mongodb.com/version/588b57893ff1224075014cebo
> Factor out stopping mongo-orchestration

- .evergreen/config.yml
Before this change the "install dependencies" pre hook was silently skipped, see https://jira.mongodb.org/browse/EVG-763.
> Fix "install dependencies" function definition

- .evergreen/run-orchestration.sh
With this change mongo-orchestration's dependencies are not fetched from PyPi:
```
[2017/02/13 10:45:14.386] + pip install --upgrade git+git://github.com/mongodb/mongo-orchestration@master
[2017/02/13 10:45:14.885] Collecting git+git://github.com/mongodb/mongo-orchestration@master
[2017/02/13 10:45:14.886]   Cloning git://github.com/mongodb/mongo-orchestration (to master) to ./db/pip-LUop84-build
[2017/02/13 10:45:16.532] Requirement already up-to-date: pymongo>=3.0.2 in /usr/lib64/python2.7/site-packages (from mongo-orchestration==0.6.7)
[2017/02/13 10:45:16.577] Requirement already up-to-date: bottle>=0.12.7 in /usr/lib/python2.7/site-packages/bottle-0.12.13-py2.7.egg (from mongo-orchestration==0.6.7)
[2017/02/13 10:45:16.662] Requirement already up-to-date: CherryPy<7.1,>=3.5.0 in …
```
> Allow virtualenv to use pre-installed system packages

- .evergreen/config.yml
- .evergreen/orchestration/configs/servers/inmemory.json
- .evergreen/orchestration/configs/servers/mmapv1.json
- .evergreen/run-orchestration.sh
The change lets drivers test against standalone mongods with the mmapv1, wiredTiger, or inMemory storage engine.
Evergreen: https://evergreen.mongodb.com/version/58ae355b3ff1225d73022c73
Resolves https://github.com/mongodb-labs/drivers-evergreen-tools/issues/15.
> Add storage engine testing for standalones

- .evergreen/config.yml
Fixes https://github.com/mongodb-labs/drivers-evergreen-tools/issues/11.
The client certificate cannot be a symlink on Windows, git/Windows does not
support symlinks.
```
$ git clone git@github.com:mongodb-labs/drivers-evergreen-tools.git
Cloning into 'drivers-evergreen-tools'...
$ ls -l drivers-evergreen-tools/.evergreen/orchestration/lib
total 1
-rwxr-xr-x 1 Administrator None 24 Feb 24 22:14 client.pem
$ cat drivers-evergreen-tools/.evergreen/orchestration/lib/client.pem
../../x509gen/client.pem
$ git clone -c core.symlinks=true git@github.com:mongodb-labs/drivers-evergreen-tools.git withsymlinks
Cloning into 'withsymlinks'...
error: unable to create symlink .evergreen/orchestration/lib/client.pem (Function not implemented)
error: unable to create symlink .evergreen/x509gen/7750279a.0 …
```
> Add support for Windows SSL tests

- .evergreen/orchestration/configs/replica_sets/auth-ssl.json
- .evergreen/orchestration/configs/replica_sets/auth.json
- .evergreen/orchestration/configs/replica_sets/basic-ssl.json
- .evergreen/orchestration/configs/replica_sets/basic.json
Removed in MongoDB 3.5.7+, SERVER-29000.
> Don't start MongoDB with --nohttpinterface

- .evergreen/orchestration/configs/sharded_clusters/auth-ssl.json
- .evergreen/orchestration/configs/sharded_clusters/auth.json
- .evergreen/orchestration/configs/sharded_clusters/basic-ssl.json
- .evergreen/orchestration/configs/sharded_clusters/basic.json
ChangeStreams and retryable writes require replica sets.
> Start shards as single member replica sets.

- .evergreen/config.yml
The solaris distro no longer exists: https://engineering.mongodb.com/post/farewell-solaris
> Remove solaris distro.

- .evergreen/download-mongodb.sh
Fixes the following bug:
```
[2018/02/27 15:26:54.096] + download_and_extract 'Unknown version: 3.4 for linux-sles-12.3-s390x' 'tar zxf'
[2018/02/27 15:26:54.096] linux-sles-12.3-s390x
[2018/02/27 15:26:54.096] + MONGODB_DOWNLOAD_URL='Unknown version: 3.4 for linux-sles-12.3-s390x'
[2018/02/27 15:26:54.096] + EXTRACT='tar zxf'
[2018/02/27 15:26:54.096] Unknown version: 3.4 for linux-sles-12.3-s390x
[2018/02/27 15:26:54.096] Unknown version: 3.4 for linux-sles-12.3-s390x
[2018/02/27 15:26:54.096] + cd /data/mci/2b5053f22b5ce16489af0ed34a35dc72/src/../drivers-tools
[2018/02/27 15:26:54.096] + curl Unknown version: 3.4 for linux-sles-12.3-s390x --silent --max-time 120 --fail --output mongodb-binaries.tgz
[2018/02/27 15:28:54.641] Command failed: command [pid=20947] encountered problem: exit …
```
> Fix distro comparison on SUSE 12 Z Series

- .evergreen/orchestration/configs/replica_sets/auth-ssl.json
- .evergreen/orchestration/configs/replica_sets/auth.json
This is to work around https://jira.mongodb.org/browse/SERVER-34421
and should be reverted once that is fixed and shipped.
> Don't use arbiters in auth configs

- .evergreen/config.yml
Evergreen is removing both distros.
> Stop testing on Ubuntu 12.04 and SLES11

- .evergreen/run-orchestration.sh
Fixes https://github.com/mongodb-labs/drivers-evergreen-tools/issues/40
Patch: https://evergreen.mongodb.com/version/5aea478e2fbabe0894ee0ecb
> Prefer python -m virtualenv over using virtualenv directly

- .evergreen/run-orchestration.sh
- .evergreen/start-orchestration.sh
Moved the python/virtualenv/mongo-orchestration setup to "start-orchestration.sh" so other projects can use it without also launching a cluster.
> Factor out starting mongo-orchestration

- .evergreen/orchestration/configs/replica_sets/auth-ssl.json
- .evergreen/orchestration/configs/replica_sets/auth.json
- .evergreen/orchestration/configs/replica_sets/basic-ssl.json
- .evergreen/orchestration/configs/replica_sets/basic.json
- .evergreen/orchestration/configs/servers/auth-ssl.json
Removed in 4.2, see SERVER-35715 and SERVER-35984.
> Remove nssize and smallfiles startup options

- .evergreen/download-mongodb.sh
I've seen task system failures because curl failed.  More retries (with exponential backoff) might help.  I'd rather have a longer delay with a chance of success than false positive test failures.
> Make curl retry more times

- .evergreen/download-mongodb.sh
oops, realized I also needed the 3.6 backport of [SERVER-36944](https://jira.mongodb.org/browse/SERVER-36944). 
evg https://evergreen.mongodb.com/version/5c19806ee3c3318c0bd0954f
> Update to MongoDB 3.6.9

- .evergreen/orchestration/configs/replica_sets/auth-ssl.json
- .evergreen/orchestration/configs/replica_sets/auth.json
- .evergreen/orchestration/configs/replica_sets/basic-ssl.json
- .evergreen/orchestration/configs/replica_sets/basic.json
Fixes [PYTHON-1644](https://jira.mongodb.org/browse/PYTHON-1644): https://evergreen.mongodb.com/version/5c7ee3e532f4176c5c1f23c1
The remaining test failures are from a server change which added the `keyPattern` and `keyValue` fields to writeErrors.
> PYTHON-1644 Ensure primary starts on port 27017

- .evergreen/config.yml
- .evergreen/download-mongodb.sh
MongoDB 4.2 requires Amazon Linux 2018.
Amazon Linux 2018 also supports MongoDB>=2.4.
On amazon1-2018 _DISTRO is generated as linux-amzn-2018.03-x86_64
On linux-64-amzn _DISTRO is generated as linux-amzn64-x86_64
Other changes:
- Support download links for amazon1-2018
- Remove "latest" testing for mmapv1
Tested here: https://evergreen.mongodb.com/version/5cd0bc8a0305b95d4e163494
> PYTHON-1830 Update to Amazon Linux 2018

- .evergreen/download-mongodb.sh
They changed the url from osx to macos for 4.2 downloads
> Fix bug to test with Evergreen on 4.2 and MacOS

- .evergreen/download-mongodb.sh
Two commits: Bump 4.2 to latest version, and add Ubuntu 18.04 PPC64LE download URL. 
Note, https://jira.mongodb.org/browse/SERVER-37774 removed Ubuntu 16.04 PPC64LE, but in favor of Ubuntu 18.04 for 4.2. See the recently updated [production notes](https://docs.mongodb.com/manual/administration/production-notes/#ppc64le-mongodb-enterprise-edition).
> Bump to 4.2.2; add Ubuntu 18.04 ppc

- .evergreen/orchestration/configs/servers/basic-tls-ocsp-mustStaple.json
- .evergreen/orchestration/configs/servers/basic-tls-ocsp.json
OCSP on 4.3.x has been flag gated under a set parameter, so we need to include `--setParameter ocspEnabled=true`
Following the format for setParamter laid out in: https://github.com/mongodb-labs/drivers-evergreen-tools/blob/master/.evergreen/orchestration/configs/servers/disableTestCommands.json
> Enable OCSP support for 4.3.x servers

- .evergreen/run-orchestration.sh
- .evergreen/start-orchestration.sh
nohup recently started failing on the macos hosts with:
```
nohup: can't detach from console: Inappropriate ioctl for device
``` 
We don't need to use nohup here as evidenced by this passing python patch build: https://evergreen.mongodb.com/version/5e47126a9ccd4e19cba49c37
> Stop using nohup 

- .evergreen/download-mongodb.sh
This PR only fixes the link for cygwin*-x86_64 because that's the only set of Windows downloads using downloads.10gen.com (the rest use fastdl.mongodb.org) and it's the case that Go and .NET match in Evergreen. I'm not sure if the other cases have to be updated too.﻿
> Fix latest download link for windows

- .evergreen/ocsp/mock_ocsp_responder.py
- .evergreen/ocsp/ocsp_mock.py
Syncing mock OCSP responder with what's in current tip of master for the server (https://github.com/mongodb/mongo/commit/78fa0cdbbbaf95f211c12640f4101b9f8c5800e1)
These changes include the ones made in:
https://jira.mongodb.org/browse/SERVER-45671 
https://jira.mongodb.org/browse/SERVER-42938
> Sync mock OCSP responder

- .evergreen/download-mongodb.sh
Update MongoDB 4.4 to use v4.4-latest download. Also updates 4.2.5 and 4.0.17.
Waiting on this python patch to succeed to make sure there are no issues with the new versions: https://evergreen.mongodb.com/version/5e87cb8cd1fe07230209f4c1
> Update MongoDB 4.4 to use v4.4-latest download

- .evergreen/download-mongodb.sh
I think this was a typo? It's causing a build failure for mongomirror testing.
> Fix 4.4 download link for linux-amzn-2-x86_64

- .evergreen/download-mongodb.sh
This change allows MongoDB 2.6, 3.0, and 3.2 to start on Archlinux, see [PYTHON-2238](https://jira.mongodb.org/browse/PYTHON-2238).
Tested in python here: https://evergreen.mongodb.com/version/5ebb11f832f4174a270b681a
> PYTHON-2238 Archlinux MongoDB <= 3.2 requires LC_ALL=C

- .evergreen/orchestration/configs/servers/ecdsa-basic-tls-ocsp-mustStaple-disableStapling-singleEndpoint.json
`ecdsa-basic-tls-ocsp-mustStaple-disableStapling-singleEndpoint.json` has a typo on line 14 that is fixed here.
> Fix typo in OCSP server config file 

- .evergreen/ocsp/mock_ocsp_responder.py
Resync the mock responder per https://jira.mongodb.org/browse/SERVER-49383.
Validated with libmongoc here: https://spruce.mongodb.com/version/5f0ca3d7306615237fb06b7b/tasks
> DRIVERSEVG-2 Add host check in mock OCSP responder

- .evergreen/atlas_data_lake/README.md
- .evergreen/atlas_data_lake/build-mongohouse-local.sh
- .evergreen/atlas_data_lake/config.yml
- .evergreen/atlas_data_lake/run-mongohouse-local.sh
The Java Driver commit for ADL testing runs the `bootstrap-mongohoused` Evergreen task in the background (https://github.com/mongodb/mongo-java-driver/commit/7f6e0c3be351e9d586ca4a6271f79af654b03deb#diff-fdcefd1312a87e7c09196afa0f0633a3R227) because otherwise the server would run in the foreground and block progress for the rest of the tasks. When adding this to the Go Driver, I found that the build was taking too long and the Go tests started running before the build was complete, so they failed because there was no server running.
This PR splits the existing `run-mongohouse-local.sh` into separate `build-mongohouse-local.sh` and `run-mongohouse-local.sh` scripts. These first would be called in the foreground and the second would be in the background. The actual server startup is very …
> Split mongohoused into separate build/run scripts

- .evergreen/atlas_data_lake/config.yml
The [MHOUSE-1776 ticket](https://github.com/10gen/mongohouse/commit/99409587bc01707952e68d9b9935be0770b81cad) involved some refactors in `mongohouse`'s config files. Specifically, the `hosting` key has been removed entirely, so `frontend` and `showInternalErrors` are now top-level keys in config files. The updated docs for the new configuration can be found [here](https://github.com/10gen/mongohouse/blob/master/docs/config.md).
To ensure that the `config.yml` file here is compatible with the new ADL config structure, the hosting key has been removed and all of the keys formerly within it are now stored at the top-level.
> MHOUSE-1776: Remove hosting key from ADL config

- evergreen_config_generator/evergreen_config_generator/functions.py
This change is necessary to support the C driver's new mongohouse test.
> Add ability to set background parameter for tasks

- .evergreen/config.yml
- .evergreen/orchestration/require-api-version.js
- .evergreen/run-orchestration.sh
This introduces a new `REQUIRE_API_VERSION` variable into the setup process for mongo-orchestration. For now, the run-orchestration.sh script will connect to the started cluster and run a `setParameter` command to enable `requireApiVersion` if the variable is set to a non-zero value.
Once PyMongo and mongo-orchestration are able to deal with the versioned API we can remove the workaround and start clusters from config files that include the requireApiVersion parameter.
> Support requireApiVersion parameter for standalone servers

- .evergreen/atlas_data_lake/config.yml
MHOUSE-1860 (merged today: https://github.com/10gen/mongohouse/pull/1839) changed the bindAddrs array to a simple string.  atlas_data_lake/config.yml needs to reflect that change to allow continued successful testing  :)
> MHOUSE-1860: reflect bindAddrs array to bindAddr string in mongohouse

- .evergreen/orchestration/configs/servers/versioned-api-testing.json
The new mongo-orchestration config starts a standalone server that enables the `acceptAPIVersion2` parameter. This is required to run the versioned API spec tests that test deprecated commands.
This config is only compatible with server versions 4.9 and newer and will fail to start on older server versions. Drivers can use this config in place of the `basic` config when testing against `latest`, but may also choose to create a separate build config that only tests versioned API tests against this config specifically.
// cc @benjirewis since I can't add you as a reviewer.
> Add a mongo-orchestration config for versioned API tests

- .evergreen/run-orchestration.sh
- .evergreen/start-orchestration.sh
- README.md
- action.yml
To help with transitioning away from travis-ci, this PR adds support for installing and launching MongoDB in a GitHub Action workflow.
Usage is documented in the readme. Most settings available to `run-orchestration.sh` are exposed as inputs to the GitHub Action. The URI of the launched cluster is exposed as an output and can be used in a subsequent build step:
```yaml
- id: setup-mongodb
uses: mongodb-labs/drivers-evergreen-tools@master
with:
version: ${{ matrix.mongodb-version }}
- name: "Run tests"
run: "run-tests.sh"
env:
MONGODB_URI: ${{ steps.setup-mongodb.outputs.cluster-uri }}
```
As `virtualenv` is not available on GitHub Actions, mongo-orchestration was not installed. I believe that installing it conditionally was not intended. Please let me know if you anticipate that change …
> Add GitHub Action metadata file to set up MongoDB

- .evergreen/auth_aws/activate_venv.sh
Adds a utility script that can be used to reduce boilerplate around using virtualenv for the AWS auth tests.
> DRIVERS-1462: Add script for using venv for AWS auth

- .evergreen/download-mongodb.sh
This change fixes the download links for Centos 6 which we use for performance testing. Centos 6 is compatible with the RHEL 6.2 releases. Tested here: https://spruce.mongodb.com/version/601aeb54d1fe0705740e9e26
The old behavior was that Centos 6 used the "generic" linux releases which only support up to MongoDB 4.0. Now all versions are supported (including TLS support).
> PYTHON-2537 Fix mongodb download links for Centos 6

- .evergreen/orchestration/configs/sharded_clusters/auth-ssl.json
- .evergreen/orchestration/configs/sharded_clusters/auth.json
- .evergreen/orchestration/configs/sharded_clusters/basic-ssl.json
- .evergreen/orchestration/configs/sharded_clusters/basic.json
- .evergreen/orchestration/configs/sharded_clusters/disableTestCommands.json
- .evergreen/orchestration/configs/sharded_clusters/mmapv1.json
After #25, this is the second attempt to introduce three-member replica sets for shards. Note that I've made this a PSS replica set, while the original change used a PSA replica set. Let me know if I should change this.
> Use three-member replica sets for shards

- .github/workflows/tests.yml
I noticed this while verifying changes from #134, we should probably test the GitHub Action portion of the file as well. This sets up a single build that tests the three topologies with auth and ssl. I've cherry-picked a commit from #134 to this PR as well to ensure that we replace absolute path in mo configs when running as GitHub action.
> Setup GitHub action testing

- .evergreen/atlas_data_lake/build-mongohouse-local.sh
- .evergreen/compile-unix.sh
- .evergreen/compile-windows.sh
- .evergreen/compile.sh
- .evergreen/config.yml
- .evergreen/download-mongodb.sh
- .evergreen/install-dependencies.sh
- .evergreen/make-docs.sh
- .evergreen/make-release.sh
- .evergreen/run-atlas-proxy.sh
- .evergreen/run-orchestration.sh
- .evergreen/run-tests.sh
- .evergreen/start-orchestration.sh
- .evergreen/stop-orchestration.sh
- evergreen_config_generator/evergreen_config_generator/__init__.py
- evergreen_config_generator/evergreen_config_generator/functions.py
DRIVERS-1596
The `xtrace` shell option prints all commands that are executed, which may reveal sensitive information. It also clutters the build logs, making debugging issues a lot harder.
While it's useful to use `xtrace` to ensure commands and options are assembled correctly, this should only be used while developing and not as part of the regular usage.
> DRIVERS-1596 Remove usages of xtrace in shell scripts

- .evergreen/config.yml
- .evergreen/serverless/create-instance.sh
- .evergreen/serverless/delete-instance.sh
- .evergreen/serverless/get-instance.sh
[DRIVERS-1603](https://jira.mongodb.org/browse/DRIVERS-1603)
This PR introduces the scripts necessary for drivers to create and delete serverless instances on demand as part of their test runs, as well as an example evergreen config that uses does so. See [here](https://evergreen.mongodb.com/version/6066352d2a60ed028ace6af7) for an example of the Swift driver using them to run the CRUD tests against a serverless instance.
Once the proxy implements some of the stuff we requested, I'll open up a new PR on the specs repo with drivers instructions on how to use these and what tests to run.
> DRIVERS-1603 Introduce scripts for provisioning and reaping serverless instances

- .evergreen/orchestration/configs/servers/versioned-api-testing.json
[SERVER-55317](https://jira.mongodb.org/browse/SERVER-55317) renamed `acceptAPIVersion2` to `acceptApiVersion2`, so we need to update the config that uses this parameter.
I did a [test patch](https://spruce.mongodb.com/version/6070db205623432f40f2a80c/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) with the Swift driver by switching our config to rely on this branch to confirm the server gets started up correctly with the renamed parameter.
This will "fix" CI for drivers, but they will now start skipping the relevant tests, as the runner will check if the old parameter name was set on the server and find it was not, so as @ShaneHarvey notes on [DRIVERS-1649](https://jira.mongodb.org/browse/DRIVERS-1649) those tests also need to be updated.
> DRIVERS-1649 acceptAPIVersion2 -> acceptApiVersion2

- .evergreen/config.yml
- .evergreen/run-load-balancer.sh
Generates a HAProxy configuration and then runs with two frontends that connect to a single mongos or 2 mongoses.
Usage:
```bash
./load-balancer.sh start
./load-balancer.sh stop
```
Will set `SINGLE_MONGOS_LB_URI` and `MULTI_MONGOS_LB_URI` env variables as the host:port to those load balancers.
TODO:
Reference PR of how to run on Evergreen: https://github.com/mongodb/node-mongodb-native/pull/2787
> NODE-3212: Adding Evergreen Load Balancer Config

- .evergreen/run-load-balancer.sh
This PR bumps the connect timeout in `run-load-balancer.sh` to 10 seconds, which matches the driver's default for `connectTimeoutMS` and the idle timeouts to 30 minutes, which should be sufficient to ensure that test runners do not encounter unexpected network errors due to severed connections.
> Bump idle and connect timeouts in run-load-balancer.sh

- .evergreen/atlas_data_lake/build-mongohouse-local.sh
DRIVERS-1733 Atlas Data Lake build script locations were updated and this change updates the references to match as well as the required go version
> DRIVERS-1733 update atlas data lake build script location reference

- .evergreen/run-load-balancer.sh
I still need to test this in EVG. Here's the local output:
```
$ .evergreen/run-load-balancer.sh start
The MONGODB_URI environment variable is required!
For example:
MONGODB_URI="mongodb://localhost:27017,localhost:27018/
or:
MONGODB_URI="mongodb://user:password@localhost:27017,localhost:27018/?authSource=admin&tls=true
```
```
$ sudo MONGODB_URI='mongodb://user:password@localhost:27017,localhost:27018/?authSource=admin' .evergreen/run-load-balancer.sh start
Password:
Starting HAProxy...
Single Mongos LB: mongodb://user:password@127.0.0.1:8000/?authSource=admin&loadBalanced=true
Multiple Mongos LB: mongodb://user:password@127.0.0.1:8001/?authSource=admin&loadBalanced=true
```
> Make load balancer script easy to run locally

- .evergreen/config.yml
- .evergreen/serverless/create-instance.sh
Tested locally and the tests pass without any API version specified, so this PR updates the serverless expansion to no longer include it.
> DRIVERS-1603 Drop API version requirement from serverless testing

- .evergreen/serverless/create-instance.sh
There are several problems on Windows:
1. `python3` call does not work
2. JSON parser adds a `CRLF` into result for some reason
3. Bash equality comparison `==` does not work
Example fail on Windows: https://evergreen.mongodb.com/task_log_raw/dot_net_driver_serverless_tests__os~windows_64_serverless_tests_patch_cf62d156f72a517c4bb61046ddb23104f58ece0c_60ac0c881e2d173e5cf09858_21_05_24_20_29_13/0?type=T#L181
Patch build with the changes: https://evergreen.mongodb.com/task/dot_net_driver_serverless_tests__os~windows_64_serverless_tests_patch_cf62d156f72a517c4bb61046ddb23104f58ece0c_60adb234e3c3312c2ce547fa_21_05_26_02_29_14
> DRIVERS-1603 Update serverless scripts to run on Windows

- .evergreen/serverless/create-instance.sh
Since the AWS are moving behind a load balancer, we need to temporarily switch to creating the instances on GCP.
> DRIVERS-1603 Switch instance creation to GCP

- .evergreen/run-load-balancer.sh
Since it is easy to forget to set MONGODB_URI if stopping the load balancer as part of an evergreen "post" task, which ignores script errors.
> DRIVERS-1833 do not require MONGODB_URI if stopping load balancer

- .evergreen/serverless/get-instance.sh
This PR updates `get-instance.sh` to use the private API endpoint which exposes the full connection string as opposed to just the SRV one as the public endpoint does.
> DRIVERS-1603 Use private API endpoint in get-instance.sh

- .evergreen/atlas_data_lake/build-mongohouse-local.sh
Node driver [Evergreen patch](https://spruce.mongodb.com/version/60f6dbeed6d80a28405ea678/tasks)
> DRIVERS-1858: update mongohouse build script paths

- .evergreen/auth_aws/activate_venv.sh
- .evergreen/csfle/activate_venv.sh
Actually checks that `$FIRST_RUN` isn't unset in dependency install and removes unnecessary brackets in the `PYTHON_BINARY` if chain.
> Fix activate_venv shell script typos

- .evergreen/download-mongodb.sh
In particular, the C driver requires [SERVER-58794](https://jira.mongodb.org/browse/SERVER-58794), which was fixed in 5.0.2, for passing tests in https://github.com/mongodb/mongo-c-driver/pull/848. The C driver has its own copy. It is not blocked on this PR.
> Update to 5.0.2, 4.0.26, and 4.4.8

- .evergreen/serverless/create-instance.sh
This updates scripts in anticipation of GCP being fronted by a load balancer.
Serverless will no longer offer a test instance without a load balancer.
This adds a LOADBALANCED environment variable to opt-in to switching to a load balanced cluster backed by `AWS`. The rationale for making this opt-in is to prevent causing test failures on drivers that already have serverless tests implemented until they implement changes in DRIVERS-1603.
I will merge this before https://github.com/mongodb/specifications/pull/1053.
> DRIVERS-1882 update serverless scripts to use AWS

- .evergreen/csfle/activate_venv.sh
During development of CDRIVER-4225, a couple CSE task failures on Evergreen due to Python environment setup failure were encountered. This PR introduces changes that resolve some of these failures.
1. Add server toolchain python3 to list of candidates
The zSeries variant does not have a python3 executable available in any of the existing set of paths inspected. [This commit](https://github.com/mongodb-labs/drivers-evergreen-tools/commit/c5fd810d5f5f7b95c49a1fdda670f244062907ad) adds the python3 executable provided by the server toolchain (already being used for GCC executable) as a last resort to the list of candidates.
2. Pin cryptography to permit use of `CRYPTOGRAPHY_DONT_BUILD_RUST`
The `cryptography` package was [updated to require the Rust toolchain as a …
> Address miscellaneous Python-related CSE Evergreen test failures

- .evergreen/socks5srv.py
- Spec PR: https://github.com/mongodb/specifications/pull/1103
- Node.js driver PR that makes use of this script:
https://github.com/mongodb/node-mongodb-native/pull/3041
> DRIVERS-1357: Add socks5srv.py helper script

- .evergreen/serverless/create-instance.sh
Remove evergreen project name from serverless instance name created in .evergreen/serverless/create-instance.sh
Tested with the Go driver `test-serverless` task:
https://spruce.mongodb.com/version/61b8f3089ccd4e11488b0152
Evergreen project names can conflict with Atlas cluster name limitations: https://docs.atlas.mongodb.com/reference/atlas-limits/#label-limits.
I did not see a clear benefit to including the evergreen project name in the serverless instance name. I chose to use a fixed `DRIVERTEST`.
> DRIVERS-2001 remove $PROJECT from create-instance

- .evergreen/orchestration/configs/sharded_clusters/load-balancer-ssl.json
- .evergreen/orchestration/configs/sharded_clusters/load-balancer.json
- .evergreen/run-load-balancer.sh
- .evergreen/run-orchestration.sh
- .evergreen/start-orchestration.sh
Adds new mongo orchestration configurations for sharded clusters when using a load balancer to specify the load balancer port config option to the mongoses. Requires that a new `LOAD_BALANCER` environment variable is set (to any value) to load the new configs and will configure the mongoses to ports 27050 and 27051, and essentially replaces the old `FAKE_MONGODB_SERVICE_ID` that drivers can now remove and run the lb tests against "latest". Updates the haproxy configuration when running the load balancer to point at these new ports.
Node implementation: https://github.com/mongodb/node-mongodb-native/pull/3089
Current Node patch build: https://spruce.mongodb.com/version/61f09db81e2d1776cfb6c7cf/tasks
> feat(DRIVERS-1983): add load balancer port in config

- .evergreen/config.yml
- .evergreen/run-orchestration.sh
https://jira.mongodb.org/browse/DRIVERS-1983
These are changes I found helpful when implementing DRIVERS-1983. Most notably, the `LOAD_BALANCER` env var needs to be passed when invoking `run-orchestration.sh`.
> DRIVERS-1983: Update config examples for load balancer changes

- .evergreen/orchestration/configs/replica_sets/auth-ssl.json
- .evergreen/orchestration/configs/replica_sets/auth.json
DRIVERS-2213: Revert "Don't use arbiters in auth configs" since SERVER-34421 has been fixed.
This reverts commit a8723971bb0d9ce6bfefdf3cc42c661b856e4706.
> DRIVERS-2213: Revert "Don't use arbiters in auth configs" since SERVER-34421 has been fixed.

- .evergreen/serverless/create-instance.sh
The introduction of f-strings dates back to https://github.com/mongodb-labs/drivers-evergreen-tools/commit/36655d1ee6cfdde2bfa870b6caff96bedcb41811. That syntax requires Python 3.6+, which is not available on all build hosts (e.g. debian92-small has Python 3.5.x).
> Replace f-strings with %-operator

- .evergreen/auth_aws/aws_e2e_assume_role.js
- .evergreen/auth_aws/aws_e2e_ec2.js
- .evergreen/auth_aws/aws_e2e_regular_aws.js
- .evergreen/auth_aws/lib/ecs_hosted_test.js
[DRIVERS-2221](https://jira.mongodb.org/browse/DRIVERS-2221)
[SERVER-57369](https://jira.mongodb.org/browse/SERVER-57369) recently removed support for auth as multiple, simultaneous users. Updates our AWS scripts to logout before running authentication functions (as the server did with [this commit](https://github.com/10gen/mongo-enterprise-modules/commit/536a2e918d6fae3334b0ca6cb3d789914db73164)).
> DRIVERS-2221 Fix AWS scripts relying on multi-authentication

- .evergreen/atlas_data_lake/build-mongohouse-local.sh
DRIVERS-2227
Updates the Go version in the ADL build script from Go 1.16 to Go 1.17, as ADL now requires 1.17+ to build.
Here is the test [now passing](https://spruce.mongodb.com/version/62261f3f1e2d1705a6e15090/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) in the Go driver.
> DRIVERS-2227 Update Go version in ADL build script

- .evergreen/download-mongodb.sh
https://jira.mongodb.org/browse/PYTHON-3192
Fixes these download errors:
```
[2022/03/31 07:19:22.399] linux-ubuntu-18.04-s390x
[2022/03/31 07:19:22.399] http://downloads.10gen.com/linux/mongodb-linux-s390x-enterprise-ubuntu1804-4.2.18.tgz
[2022/03/31 07:19:22.598] gzip: stdin: not in gzip format
[2022/03/31 07:19:22.598] tar: Child returned status 1
[2022/03/31 07:19:22.598] tar: Error is not recoverable: exiting now
```
Passing patch here: https://spruce.mongodb.com/version/6245ff0a1e2d17279da0822d/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> PYTHON-3192 Fix download links for zSeries

- .evergreen/serverless/create-instance.sh
- .evergreen/serverless/delete-instance.sh
- .evergreen/serverless/get-instance.sh
https://jira.mongodb.org/browse/DRIVERS-1967
Updates serverless scripts to use a multi-tenant MongoDB (MTM) deployment with the SINGLE_TARGET_SERVERLESS_DEPLOYMENT feature flag enabled (CLOUDP-117288).
This simplifies much of the original logic since there is now only a single SRV URI. For BC, create-instance.sh still outputs all of the original expansions. Those can be cleaned up at a later date after all downstream drivers migrate to the new expansions.
The create-instance.sh script was also updated to solicit an explicit instance name (e.g. generated within the Evergreen config).
> DRIVERS-1967: Serverless testing uses load balancer fronting single proxy

- .evergreen/download-mongodb.sh
Also updates to the latest rapid, 5.0, 4.4, and 4.2 releases and removes 5.1 which is unused.
> DRIVERS-2299 Add MongoDB 6.0 download links and platforms

- .evergreen/download-mongodb.sh
RHEL 8.2 ARM was added in 4.4.2 and is supported on 4.4, 5.0, and 6.0: https://jira.mongodb.org/browse/SERVER-48282
> Add RHEL 8.2 ARM download and update to 6.0.0-rc4

- .evergreen/mongodl.py
I am running into issues attempting to use mongodl.py on RHEL 70. RHEL 70 only has Python <=3.6 available, and the deterministic parameter was added in version 3.8 (https://docs.python.org/3/library/sqlite3.html#sqlite3.Connection.create_function). Given that this parameter only performs optimizations, and does not effect the output, it seems sensible to remove it so that mongodl.py can be used on more platforms.
> Remove usage of deterministic keyword argument in mongodl.py

- .evergreen/auth_aws/activate_venv.sh
- .evergreen/csfle/activate_venv.sh
Attempting to fix https://jira.mongodb.org/browse/DRIVERS-2346
Testing here: https://spruce.mongodb.com/version/6297f4961e2d1748f0c12306
> DRIVERS-2346 Use venv instead of virtualenv

- .evergreen/download-mongodb.sh
6.0.0-rc10 includes [SERVER-66901](https://jira.mongodb.org/browse/SERVER-66901), which is needed for [PHPLIB-884](https://jira.mongodb.org/browse/PHPLIB-884).
> Bump VERSION_60 to 6.0.0-rc10

- .evergreen/download-mongodb.sh
6.0.0-rc11 is available for download. See https://jira.mongodb.org/browse/STAR-2918.
This may be necessary to test changes with https://jira.mongodb.org/browse/SERVER-66663.
> update 6.0.0 version to rc11

- .evergreen/start-orchestration.sh
This change makes it easier to use run-orchestration.sh locally by making MONGODB_BINARIES default to the place that download-mongodb.sh downloads to.
For example:
```
$ LOAD_BALANCER=true TOPOLOGY=sharded_cluster MONGODB_VERSION=6.0 DRIVERS_TOOLS=/Users/shane/git/drivers-evergreen-tools MONGO_ORCHESTRATION_HOME=/Users/shane/git/drivers-evergreen-tools/.evergreen/orchestration ~/git/drivers-evergreen-tools/.evergreen/run-orchestration.sh
+ AUTH=noauth
+ SSL=nossl
+ TOPOLOGY=sharded_cluster
+ LOAD_BALANCER=true
+ STORAGE_ENGINE=
+ REQUIRE_API_VERSION=
+ DISABLE_TEST_COMMANDS=
+ MONGODB_VERSION=6.0
+ MONGODB_DOWNLOAD_URL=
+ ORCHESTRATION_FILE=
++ date +%s
+ DL_START=1657227910
++ dirname /Users/shane/git/drivers-evergreen-tools/.evergreen/run-orchestration.sh
+ …
```
> Sensible default for MONGODB_BINARIES

- .evergreen/mongodl.py
We cannot _perfectly_ reliably guess the URL to the latest builds, but we can usually get it right.
> Support "latest-build" version in mongodl

- .evergreen/orchestration/configs/replica_sets/auth-ssl.json
- .evergreen/orchestration/configs/replica_sets/auth.json
- .evergreen/orchestration/configs/replica_sets/basic-ssl.json
- .evergreen/orchestration/configs/replica_sets/basic.json
- .evergreen/orchestration/configs/replica_sets/disableTestCommands.json
- .evergreen/orchestration/configs/replica_sets/mmapv1.json
- .evergreen/orchestration/configs/replica_sets/single-node-auth-ssl.json
- .evergreen/orchestration/configs/replica_sets/single-node-auth.json
- .evergreen/orchestration/configs/servers/auth-aws.json
- .evergreen/orchestration/configs/servers/auth-ssl.json
- .evergreen/orchestration/configs/servers/auth.json
- .evergreen/orchestration/configs/servers/basic-ssl.json
- .evergreen/orchestration/configs/servers/basic.json
- .evergreen/orchestration/configs/servers/disableTestCommands.json
- .evergreen/orchestration/configs/servers/ecdsa-basic-tls-ocsp-disableStapling-singleEndpoint.json
- .evergreen/orchestration/configs/servers/ecdsa-basic-tls-ocsp-disableStapling.json
- .evergreen/orchestration/configs/servers/ecdsa-basic-tls-ocsp-mustStaple-disableStapling-singleEndpoint.json
- .evergreen/orchestration/configs/servers/ecdsa-basic-tls-ocsp-mustStaple-disableStapling.json
- .evergreen/orchestration/configs/servers/ecdsa-basic-tls-ocsp-mustStaple-singleEndpoint.json
- .evergreen/orchestration/configs/servers/ecdsa-basic-tls-ocsp-mustStaple.json
- .evergreen/orchestration/configs/servers/inmemory.json
- .evergreen/orchestration/configs/servers/mmapv1.json
- .evergreen/orchestration/configs/servers/rsa-basic-tls-ocsp-disableStapling-singleEndpoint.json
- .evergreen/orchestration/configs/servers/rsa-basic-tls-ocsp-disableStapling.json
- .evergreen/orchestration/configs/servers/rsa-basic-tls-ocsp-mustStaple-disableStapling-singleEndpoint.json
- .evergreen/orchestration/configs/servers/rsa-basic-tls-ocsp-mustStaple-disableStapling.json
- .evergreen/orchestration/configs/servers/rsa-basic-tls-ocsp-mustStaple-singleEndpoint.json
- .evergreen/orchestration/configs/servers/rsa-basic-tls-ocsp-mustStaple.json
- .evergreen/orchestration/configs/servers/versioned-api-testing.json
- .evergreen/orchestration/configs/servers/wiredtiger.json
DRIVERS-2388
Removes the `journal` option from all mongo-orchestration configs. Server version v6.1.0-rc0 no longer supports the `journal` configuration block, so specifying `journal` in these configs causes system failures with the latest server version. `journal` always defaults to `true`, so explicitly specifying it is also redundant.
> DRIVERS-2388 Remove journal from all configs.

- .evergreen/download-mongodb.sh
[DRIVERS-2405](https://jira.mongodb.org/browse/DRIVERS-2405)
Enterprise auth tests were [failing](https://evergreen.mongodb.com/task/mongo_go_driver_enterprise_auth_tests__os_ssl_32~ubuntu1604_64_go_1_17_test_enterprise_auth_gssapi_a0066218d8942310155b64057c094448e90e3356_22_07_28_16_22_22) on Ubuntu 16.04 in the Go driver because we were unable to fetch the `crypt_shared` package on "latest". "latest" on Ubuntu 16.04 is less than 6.0, so crypt_shared is not even available. We should not fetch crypt_shared on OSes where "latest" is less than 6.0.
Here's a [patch](https://spruce.mongodb.com/version/62e424579ccd4e1b430c6cf7/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) of these changes fixing the auth tests in Go.
> DRIVERS-2405 Do not include crypt_shared on latest when less than 6.0.

- .evergreen/csfle/set-temp-creds.sh
- Do not print newline in `set-temp-creds.sh`.
This [patch build](https://spruce.mongodb.com/task/mongo_go_driver_tests_42_plus_zlib_zstd_support__version~latest_os_ssl_40~windows_64_go_1_17_test_replicaset_auth_ssl_patch_f87317a97462447361004797b2e6d1023c61eaf4_62e805a0e3c3313b75ef96fb_22_08_01_16_56_02/tests?execution=0&sortBy=STATUS&sortDir=ASC) in the Go driver reproduces an HTTP 400 reported in PYTHON-3384.
[The logs](https://evergreen.mongodb.com/lobster/evergreen/test/mongo_go_driver_tests_42_plus_zlib_zstd_support__version~latest_os_ssl_40~windows_64_go_1_17_test_replicaset_auth_ssl_patch_f87317a97462447361004797b2e6d1023c61eaf4_62e805a0e3c3313b75ef96fb_22_08_01_16_56_02/0/test/#bookmarks=0%2C61&l=1&shareLine=16) show an extra `\r` appended to the session token header: …
> MONGOCRYPT-457 do not print newline in set-temp-creds.sh

- .evergreen/csfle/set-temp-creds.sh
This improves https://github.com/mongodb-labs/drivers-evergreen-tools/pull/220 by adding back Python 2 support for CSFLE test setup. This is needed for maximum compat. For example the legacy python driver v3 still tests with Python 2.
> MONGOCRYPT-457 Add back Python 2 support for CSFLE test setup

- .evergreen/csfle/gcpkms/create-and-setup-instance.sh
- Use devprod-drivers as default GCP project.
The integration tests added in DRIVERS-2377 were relying on a personal account.
https://jira.mongodb.org/browse/BUILD-15386 provided a service account with necessary permissions.
The project associated with the account is different.
> DRIVERS-2377 use devprod-drivers project

- .evergreen/csfle/gcpkms/create-and-setup-instance.sh
- Specify a non-root ssh user for GCP script.
- Capture output of last failed ssh attempt.
The GCE `debian-11` instance disables root login over ssh. The contents of `/etc/ssh/sshd_config` contain `PermitRootLogin no`.
The default user on the Evergreen distro `rhel70-small` is `root`. This appears to be the cause of observed [task failures on the ssh command](https://spruce.mongodb.com/task/mongo_java_driver_testgcpkms_variant_testgcpkms_task_patch_6a2389083a9b744bb771fdf2ce767d84adda7803_62f256f10ae606469f19ddb6_22_08_09_12_45_37/logs?execution=0) with the message `Permission denied (publickey)`.
> DRIVERS-2377 Specify a non-root ssh user

- .evergreen/download-mongodb.sh
- Fix `CRYPT_SHARED_LIB_PATH` expansion for any working directory.
`download_and_extract_crypt_shared` downloads the shared library to the current working directory.
The `CRYPT_SHARED_LIB_PATH` expansion added in https://github.com/mongodb-labs/drivers-evergreen-tools/pull/221/files assumes `run-orchestration.sh` is run from a directory containing `drivers-evergreen-tools`.
The Go driver does not run `run-orchestration.sh` from a directory containing `drivers-evergreen-tools`. From inspecting a patch build:
- `run-orchestration.sh` is run from this directory: `/data/mci/d5418d166b5347697731a2d43e6fae62`
- `drivers-evergreen-tools` is located in this directory: `/data/mci/d5418d166b5347697731a2d43e6fae62/src/go.mongodb.org/mongo-driver/../drivers-tools`
This results in an incorrect …
> CSHARP-4254 use pwd for download_and_extract_crypt_shared

- .evergreen/download-mongodb.sh
On an Apple M1, the x64 server can run via Rosetta 2, but the CSFLE shared library cannot. I'm currently blocked on adding Apple M1 support to the .NET/C# Driver because loading the CSFLE shared library fails in Evergreen.
> DRIVERS-2429: Added Apple M1 downloads.

- .evergreen/atlas_data_lake/build-mongohouse-local.sh
Patch on node using this branch: https://spruce.mongodb.com/task/mongo_node_driver_next_ubuntu_18.04_gallium_test_atlas_data_lake_patch_8c63447f8bcfb6a71d1838444fd87d9c251106b0_6331ee6956234317acab0ba2_22_09_26_18_24_53/logs?execution=1
ADL requires 18+, I put 19 to hopefully kick bumping this again a little further down the road.
edit: Could not use 19, wasn't available on the host
> DRIVERS-2450: bump ADL golang version to 1.18

- .evergreen/utils.sh
If two or more tasks on Evergreen invokes `venvactivate` in parallel, there is the possibility that the call to `dos2unix` may race and subsequently fail with the following error:
```
dos2unix: problems renaming 'kmstlsvenv/Scripts/d2utmpDAd1Fo' to 'kmstlsvenv/Scripts/activate': Permission denied
output file remains in 'kmstlsvenv/Scripts/d2utmpDAd1Fo'
dos2unix: problems converting file kmstlsvenv/Scripts/activate
```
This PR proposes moving the `dos2unix` call into `venvcreate` immediately after creation of `$VENVPATH` to allow for safe subsequent parallel invocations of `venvactivate`.
> Move dos2unix from venvactivate to venvcreate

- .evergreen/csfle/azurekms/README.md
- .evergreen/csfle/azurekms/create-and-setup-vm.sh
- .evergreen/csfle/azurekms/create-vm.sh
- Respect environment variable `AZUREKMS_IMAGE`.
- Change default Azure VM image to latest version of Debian 11.
Debian 10 does not have packages for Java 17. Using Debian 11 is [consistent with GCP testing](https://github.com/mongodb-labs/drivers-evergreen-tools/blob/51de752387e2c0873702d054e92440807d1c0aa8/.evergreen/csfle/gcpkms/create-and-setup-instance.sh#L16).
If a driver requires Debian 10, set the environment variable `AZUREKMS_IMAGE=Debian:debian-10:10:0.20220911.1135`.
Tested with the C driver patch build: https://spruce.mongodb.com/version/6363b6402a60ed60575d1fb6
> DRIVERS-2411 fix handling of `AZUREKMS_IMAGE`

- .evergreen/csfle/activate-kmstlsvenv.sh
- .evergreen/find-python3.sh
- .evergreen/venv-utils.sh
This PR is the first of several PRs whose goal is to improve the robustness and hygiene of DET shell scripts by taking full advantage of the features provided by Bash.
This PR is focused on providing improved alternatives to scripts that pertain to Python virtual environment creation and activation. This PR does _not_ change the behavior of any existing scripts. Followup PRs will attempt to incorporate these new scripts into existing scripts, which may change their behavior.
This file defines four functions:
- is_python3
- is_venv_capable
- is_virtualenv_capable
- find_python3
The primary purpose of this file is to provide `find_python3`, which is implemented in terms of the other three functions.
`find_python3` aims to serve as a reliable and comprehensive utility function to replace the …
> Add hygienic alternatives to Python virtual environment scripts

- .evergreen/config.yml
- .evergreen/download-mongodb.sh
- .evergreen/serverless/create-instance.sh
- .evergreen/serverless/download-crypt.sh
[DRIVERS-2459](https://jira.mongodb.org/browse/DRIVERS-2459)
[DRIVERS-2400](https://jira.mongodb.org/browse/2400) asks drivers to run CSFLE tests on Serverless, which require mongocryptd or crypt_shared to run. Since this is installed in run-orchestration.sh which isn't invoked on Serverless, this PR adds the necessary download steps to create-instance.sh. A new environment variable allows disabling this download in case people want to test this locally (where they typically would have mongocryptd or crypt_shared installed already).
For now the script always downloads the rapid release version - this is to avoid parsing the reported Serverless version and deducing the correct version string to pass along (e.g. `6.1.3` would have to be replaced with `rapid`). This can be added in a …
> DRIVERS-2459: Add script to download mongocryptd and crypt_shared

- .evergreen/csfle/activate-kmstlsvenv.sh
- .evergreen/find-python3.sh
- .evergreen/venv-utils.sh
This PR is a followup to https://github.com/mongodb-labs/drivers-evergreen-tools/pull/236 and applies a critical patch to [DRIVERS-2497](https://jira.mongodb.org/browse/DRIVERS-2497) required by Windows distros.
This PR is verified by [this patch](https://spruce.mongodb.com/version/636d66b17742ae6eb49bfedf/tasks).
The [tests](https://spruce.mongodb.com/version/63485ef132f417225c2244fb) used to validate behavior in https://github.com/mongodb-labs/drivers-evergreen-tools/pull/236 did not account for the presence of [pre commands](https://github.com/mongodb-labs/drivers-evergreen-tools/blob/f5d1c049948718218b006c0732990e1c642cbb13/.evergreen/config.yml#L424) which modifies the environment such that it does not accurately reflect the environment used by Drivers, such as [modifying the `$PATH` …
> DRIVERS-2497 Fix paths on Cygwin and Python package dependencies

- action.yml
See: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
This eliminates deprecation notices in our workflow runs. Related to another PR I opened in https://github.com/cmb69/setup-php-sdk/pull/21, although that was for Windows.
> Migrate deprecated set-output command to use $GITHUB_OUTPUT

- .evergreen/csfle/gcpkms/create-and-setup-instance.sh
- .evergreen/csfle/gcpkms/create-instance.sh
- .evergreen/csfle/gcpkms/delete-instance.sh
- Delete SSH keys at task completion for GCP.
- Add ConnectTimeout=10 to ssh command.
The `testgcpkms-task` task was failing with the error `The zone 'projects/devprod-drivers/zones/us-east1-b' does not have enough resources available to fulfill the request.  Try a different zone, or try again later.`. ([Example](https://spruce.mongodb.com/task/mongo_go_driver_testgcpkms_variant_testgcpkms_task_0e5ae89f1baf3d6edca093467ffd1f870b441add_22_11_28_21_11_31/logs?execution=0)).
The cause of the error was a resource limit for SSH keys created in the [GCP Project Metadata](https://cloud.google.com/compute/docs/metadata/setting-custom-metadata):
> SSH keys are stored as custom metadata under the ssh-keys key. If your metadata content or value for this key exceeds the 256 KB limit, you won't be …
> DRIVERS-2377 remove SSH keys on task completion

- .evergreen/start-orchestration.sh
Testing for https://github.com/10gen/mongo-orchestration/pull/293 and removes the now outdated workaround added in https://github.com/mongodb-labs/drivers-evergreen-tools/pull/202
> Remove outdated bottle version cap

- .evergreen/run-orchestration.sh
- .evergreen/start-orchestration.sh
A recent upgrade to [use cheroot by default instead of CherryPy](https://github.com/10gen/mongo-orchestration/pull/293) to address Python 3.11 compatibility breaks the `run-orchestration.sh` script on platforms where the [manual Python binary lookup routine](https://github.com/mongodb-labs/drivers-evergreen-tools/blob/10f1a128f09a80e4d4ac42579a0f17b81338ab81/.evergreen/start-orchestration.sh#L17) in `start-orchestration.sh` cannot find a suitably new version of Python, as observed in [this build](https://parsley.mongodb.com/evergreen/cxx_driver_debian10_release_50_compile_and_test_with_shared_libs_patch_7b4ceacb794c9e2953346d8dc9dae894315eaaf8_639ca1dd9ccd4e59daf572f8_22_12_16_16_50_37/0/task?bookmarks=0,295&selectedLine=217) (e.g. [selected a Python 2 …
> Use find-python3.sh and venv-utils.sh to create mongo orchestration venv

- .evergreen/download-mongodb.sh
- Download latest Major release of `crypt_shared` if a version matching the server is unavailable.
After this change, downloading server versions < 6.0 is expected to try to download `crypt_shared` 6.0.
The term Major comes from [MongoDB Software Lifecycle Schedules](https://www.mongodb.com/support-policy/lifecycles).
This is a request from product. Drivers only test the `crypt_shared` library with the same version of the server per DRIVERS-2355. MongoDB does not document support for using `crypt_shared` an older server version. Functionally, new versions of `crypt_shared` are expected to work with older server versions. Testing will validate that expectation and enable documenting support of new `crypt_shared` with old server versions.
Tested with [Go …
> DRIVERS-2465 Download latest Major release of `crypt_shared`

- .evergreen/auth_aws/activate-authawsvenv.sh
- .evergreen/csfle/activate-kmstlsvenv.sh
- .evergreen/find-python3.sh
- .evergreen/ocsp/activate-ocspvenv.sh
- .evergreen/start-orchestration.sh
- .evergreen/venv-utils.sh
This PR is a followup to https://github.com/mongodb-labs/drivers-evergreen-tools/pull/255 which assumed `DRIVERS_TOOLS` is defined when the script is invoked (as per `run-orchestration.sh`), which was not true (https://github.com/10gen/mongosync/pull/1180). This PR reverts to _not_ requiring `DRIVERS_TOOLS` in `start-orchestration.sh` by using `"$(dirname "${BASH_SOURCE[0]}")"` instead, taking advantage of the Bash shell requirement.
Furthermore, due to repeated instances of confusion regarding the Bash shell requirement and methods of invoking the script on Evergreen, this PR also introduces "Bash checks" to improve the quality of error messages that are encountered if a script is incorrectly invoked using i.e. `sh -c script.sh`, which does not respect the script shebangs ([sh is not …
> Add bash check and use BASH_SOURCE instead of DRIVERS_TOOLS

- .evergreen/auth_aws/activate-authawsvenv.sh
- .evergreen/csfle/activate-kmstlsvenv.sh
- .evergreen/find-python3.sh
- .evergreen/ocsp/activate-ocspvenv.sh
- .evergreen/serverless/create-instance.sh
- .evergreen/start-orchestration.sh
- .evergreen/venv-utils.sh
(Comprehensively) verified by [this patch](https://spruce.mongodb.com/version/63b5ad1630661566a4c540aa/tasks).
Followup to https://github.com/mongodb-labs/drivers-evergreen-tools/pull/257, where `$BASHPID` was selected due to (pessimistic) concern of being less likely to be user-defined (overwritten) than `$BASH`. However, lack of version information in the [Bash reference manual](https://www.gnu.org/software/bash/manual/bash.html) and failure to comprehensive test the PR missed [certain platforms](https://spruce.mongodb.com/task/mongo_node_driver_next_macos_1100_test_rapid_server_patch_fe65746a80715a42e221fdfa53b7976c6ec75446_63b5a4933e8e864403b41737_23_01_04_16_08_51/logs?execution=0) that do not support `$BASHPID`, which happens to be a Bash 4.0 or newer feature. This PR replaces all …
> Use $BASH instead of $BASHPID for old Bash compatibility

- .evergreen/start-orchestration.sh
This PR is a followup to https://github.com/mongodb-labs/drivers-evergreen-tools/pull/257 which failed to account for a `cd` prior to setting `det_evergreen_dir`, as `${BASH_SOURCE[0]}` produces a path relative to `start-orchestration.sh` _on invocation_, not an absolute path. This resulted in the subsequent sourcing of `find-python3.sh` and `venv-utils.sh` using paths relative to the new `$MONGO_ORCHESTRATION_HOME` directory rather than the working directory on invocation of `start-orchestration.sh`.
> Source DET scripts before changing directory in start-orchestration.sh

- .evergreen/csfle/gcpkms/create-and-setup-instance.sh
- .evergreen/csfle/gcpkms/create-instance.sh
- Increase boot disk size from 10GB to 20GB.
- Add `GCPKMS_DISKSIZE` option to permit configuration of boot disk size.
This is intended to address the `No space left on device` error on the C# task for the [prose test case for GCP with KMS](https://github.com/mongodb/specifications/blob/c94fefe3e14d163bedcab75a761bc14a77ec689f/source/client-side-encryption/tests/README.rst#case-2-success-1).
With this change, the `create-and-setup-instance.sh` script produces two new warnings:
```
WARNING: You have selected a disk size of under [200GB]. This may result in poor I/O performance. For more information, see: https://developers.google.com/compute/docs/disks#performance.
Created [https://www.googleapis.com/compute/v1/projects/devprod-drivers/zones/us-east1-b/instances/instancename-16692]. …
```
> DRIVERS-2377 add GCPKMS_DISKSIZE option with default 20GB

- .evergreen/csfle/activate-kmstlsvenv.sh
Related to https://github.com/OpenKMIP/PyKMIP/issues/687.
Addresses the following observed error when running `kms_kmip_server.py` after SQLAlchemy 2.0.0 is installed. The error is not observed when SQLAlchemy version is <2.0.0. The error was observed regardless of Python version.
```
Traceback (most recent call last):
File ".evergreen/csfle/kms_kmip_server.py", line 6, in <module>
from kmip.services.server import KmipServer
File ".evergreen/csfle/kmstlsvenv/lib/python3.9/site-packages/kmip/__init__.py", line 22, in <module>
from kmip.pie import client
File ".evergreen/csfle/kmstlsvenv/lib/python3.9/site-packages/kmip/pie/__init__.py", line 16, in <module>
from kmip.pie.client import ProxyKmipClient
File ".evergreen/csfle/kmstlsvenv/lib/python3.9/site-packages/kmip/pie/client.py", line …
```
> Forbid SQLAlchemy 2.0.0 to workaround InvalidRequestError exception

- .evergreen/atlas_data_lake/config.yml
- Update mongohouse config to add `hostProvider` and disable `billing`
The `run-mongohouse-local.sh` script is failing to start mongohoused and [reports this error](https://spruce.mongodb.com/task/mongo_go_driver_atlas_data_lake_test_test_atlas_data_lake_b1e7aa5b82b06ebfc32b035757cef43ac03e8869_23_01_24_18_38_30/logs?execution=1&sortBy=STATUS&sortDir=ASC):
```
$ sh .evergreen/atlas_data_lake/run-mongohouse-local.sh
*internal.Config: hostProvider not configured and <warning *internal.Config.Billing: no billing configured>
```
This appears to be caused by changes made in MHOUSE-6118. See https://mongodb.slack.com/archives/CKNS6CS72/p1674779015703769
This branch was tested with the Go driver in [this patch](https://spruce.mongodb.com/task/mongo_go_driver_atlas_data_lake_test_test_atlas_data_l …
> update mongohouse config

- .evergreen/download-mongodb.sh
- .evergreen/run-atlas-proxy.sh
- .evergreen/run-orchestration.sh
[DRIVERS-2328](https://jira.mongodb.org/browse/DRIVERS-2328)
This PR adds functionality to download the new `mongosh` shell. The legacy shell is still installed on platforms where it's available. This allows downstream users of drivers-evergreen-tools to start using `mongosh` where possible. Note that the javascript files used to test AWS auth are not compatible with `mongosh` yet, this will follow in a second step.
To test this PR in your driver before it's merged, please use the following patch:
```patch
diff --git a/.evergreen/config.yml b/.evergreen/config.yml
index be1192e..75a3150 100644
--- a/.evergreen/config.yml
+++ b/.evergreen/config.yml
@@ -92,7 +92,7 @@ functions:
cp -R ${PROJECT_DIRECTORY}/ $DRIVERS_TOOLS
else
-            git clone …
```
> DRIVERS-2328: Download mongosh alongside the legacy shell

- .evergreen/csfle/gcpkms/create-and-setup-instance.sh
- Define expansions for GCP earlier.
- Add 7200s expiration to SSH keys for GCP instances.
Changes verified with the [C driver](https://spruce.mongodb.com/version/63ed3c3757e85ad57ad2127b/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC).
The test-gcpkms task is [failing in drivers](https://spruce.mongodb.com/task/mongo_java_driver_testgcpkms_variant_testgcpkms_task_a7489266d5eced73ce129357ec1782accccf0a5a_23_02_13_19_44_46/logs?execution=0) with the message:
```
failed to ssh into 'instancename-14683'. Output of last attempt: ERROR: (gcloud.compute.ssh) INVALID_ARGUMENT: Login profile size exceeds 32 KiB. Delete profile values to make additional space.
```
Keys have been manually deleted using this [suggested solution](https://github.com/kyma-project/test-infra/issues/93#issuecomment-4572635 …
> DRIVERS-2377 Define expansions for GCP earlier

- .evergreen/find-python3.sh
- .evergreen/venv-utils.sh
Examination of Evergreen logs in recent tests revealed the use of `nounset` within some subshell functions were excluding potentially viable Python binary candidates due to the generated activation scripts not satisfying the `nounset` condition (specifically due to the `PS1` environment variable being unset). This PR removes `nounset` to improve the selection of viable Python binaries.
Recent Bash experience also revealed that declaring a variable and immediately assigning it with value of a potentially-failing command substitution can [mask the exit status of the command substitution](http://mywiki.wooledge.org/BashPitfalls#local_var.3D.24.28cmd.29). Adjusted such instances accordingly so that command substitution failures are properly detected and handled.
> Remove nounset and avoid masking exit status of command substitutions

- .evergreen/csfle/azurekms/install-az.sh
- Do not skip install of `azure-cli` if `az` is detected.
- Print `az --version`
Drivers tests [using Azure scripts are failing](https://parsley.mongodb.com/evergreen/mongo_java_driver_testazurekms_variant_testazurekms_task_a7489266d5eced73ce129357ec1782accccf0a5a_23_02_13_19_44_46/0/task?bookmarks=0,330&shareLine=298) with this message:
```
ERROR: UnrecognizedArgumentError: unrecognized arguments: --nic-delete-option Delete --data-disk-delete-option Delete --os-disk-delete-option Delete
```
The tests fail on Debian11 hosts, but not Debian10 hosts. The cause appears to be an older version of `azure-cli` being installed on `debian10`.
The script is invoking `azure vm create` with the delete options (`--nic-delete-option`, `--data-disk-delete-option`, and `--os-disk-delete-option`).
The …
> DRIVERS-2411 Do not skip install of `azure-cli` if `az` is detected

- .evergreen/auth_oidc/oidc_write_orchestration.py
SERVER-70958 merged so need the `tokenEndpoint` field back in the config, otherwise:
_"BadValue: Bad value for parameter "oidcIdentityProviders": BSON field 'IDPConfiguration.tokenEndpoint' is missing but a required field"_
> fix(DRIVERS-2415): bring back token endpoint

- .evergreen/csfle/gcpkms/remote-scripts/setup-gce-instance.sh
- run `apt-get update` in setup-gce-instance.sh
Fixes failures observed in the `test_gcpkms` task for the C driver:
```
[2023/02/28 16:31:19.508] E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/t/tiff/libtiff5_4.2.0-1%2bdeb11u3_amd64.deb  404  Not Found [IP: 146.75.34.132 80]
[2023/02/28 16:31:19.510] E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```
Fix has been verified tested with the C driver in this [patch build](https://spruce.mongodb.com/version/63ff93b25623435ea1e7befe/).
> DRIVERS-2377 run apt-get update in setup-gce-instance.sh

- .evergreen/config.yml
- Servers were failing to [start](https://spruce.mongodb.com/task/drivers_tools_tests_os_requires_36__os_requires_36~rhel72_zseries_test_auth~auth_ssl~nossl_test_3.6_sharded_cluster_6362b957e40af2ef8f4438efc719abf37b368479_23_03_17_17_44_27/tests?execution=0&sortBy=STATUS&sortDir=ASC) on Rhel 7.2 (ZSeries), move to Rhel 7.0 Small
- The build upload/fetch was [failing](https://spruce.mongodb.com/task/drivers_tools_releng_release_archive_creator_release_compile_6362b957e40af2ef8f4438efc719abf37b368479_23_03_17_17_44_27/logs?execution=0) on the Release tasks
> Fix Failing EG Builds

- .evergreen/download-mongodb.sh
6.2 was released in February, so this PR updates our rapid version to 6.2.1.
> Bump rapid version to 6.2.1

- .evergreen/orchestration/setfle2parameter.py
- .evergreen/run-orchestration.sh
- Enable `featureFlagFLE2ProtocolVersion2` if environment variable `ENABLE_featureFlagFLE2ProtocolVersion2=ON` is set in `run-orchestration.sh`
Updated scripts were tested in Go driver tests: https://github.com/mongodb/mongo-go-driver/pull/1213
Enabling `featureFlagFLE2ProtocolVersion2` is required to enable the Queryable Encryption v2 protocol. [SERVER-69563](https://jira.mongodb.org/browse/SERVER-69563) plans to enable the feature flag by default. Once the feature flag is enabled by default, the `setfle2parameter.py` script and check for `ENABLE_featureFlagFLE2ProtocolVersion2` can be removed.
> DRIVERS-2435 add option to enable `featureFlagFLE2ProtocolVersion2` 

- .evergreen/auth_oidc/Dockerfile
- .evergreen/csfle/azurekms/install-az.sh
- .evergreen/csfle/azurekms/remote-scripts/setup-azure-vm.sh
- .evergreen/csfle/gcpkms/remote-scripts/setup-gce-instance.sh
- .evergreen/install-dependencies.sh
This PR is motivated by the occasional observation of the following error (by multiple Drivers teams) when running Azure KMS tests:
```
E: Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
```
This PR proposes adding the [undocumented(?)](https://manpages.ubuntu.com/manpages/jammy/man5/apt.conf.5.html) `DPkg::Lock::Timeout` option when invoking `apt-get install` to use its built-in support for [waiting on the dpkg lock](https://salsa.debian.org/apt-team/apt/-/merge_requests/109/diffs?commit_id=93e1565796b61eb44bec39f50e09a34cbe090178) instead of triggering an immediate error. This is probably preferable to [bypassing the …
> Add DPkg::Lock::Timeout to apt-get install commands

- .evergreen/run-deployed-lambda-aws-tests.sh
Adds a new script, `.evergreen/run-deployed-lambda-aws-tests.sh` that:
- Creates a new Atlas cluster in a specific driver project
- Polls for the cluster SRV record when cluster creation is complete
- Builds the Lambda function locally
- Deploys the Lambda function to AWS.
- Queries for the Lambda function ARN.
- Invokes the Lambda function cold and frozen.
- Initiates a primary failover of the cluster in Atlas.
- Calls the frozen lambda function again.
- Deletes the Lambda function.
- Deletes the Atlas cluster.
Node impl: https://github.com/mongodb/node-mongodb-native/pull/3569
> test(DRIVERS-2384): add script for running lambda tests

- .evergreen/download-mongodb.sh
- .evergreen/run-orchestration.sh
This PR adds a new `SKIP_LEGACY_SHELL` variable to skip installing the legacy shell. This is necessary on platforms that don't have 5.0 builds which we use to download the legacy shell. It also changes the script to set `requireApiVersion` on the server to use mongosh instead of the legacy shell. While there are some platforms where mongosh is not available, I believe that we don't test the stable API on those platforms. If any drivers run into issues with this, please let me know.
The only usage of the legacy shell that is left are the AWS auth tests. These tests will be updated separately, as I'm currently not convinced they can run on mongosh at all, so they might have to be rewritten.
To test these changes in your driver before the PR is merged, apply the patch below. This should …
> DRIVERS-2328: Allow disabling usage of legacy shell

- .evergreen/download-mongodb.sh
https://jira.mongodb.org/browse/DRIVERS-2618
The RedHat / CentOS 7.2 s390x, RedHat / CentOS 8.1 ppc64le, and RedHat / CentOS 8.3 s390x releases are not available for 7.0 but I added links for them anyway since I'm not sure they have been officially removed.
I also updated to 6.3.1, 5.0.17, and 4.4.21.
> DRIVERS-2618 Add download support for MongoDB 7.0

- .evergreen/download-mongodb.sh
The rest of the backported versions were updated in #299
Needed for https://jira.mongodb.org/browse/PYTHON-3659
> DRIVERS-2605 Update 6.0 server version

- .evergreen/download-mongodb.sh
Here is a patch build that shows the links working: https://spruce.mongodb.com/version/6467869056234346b7ad8f01/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
Most of the tasks are failing, but for reason unrelated to the server download.
> add download links for RHEL9

- .evergreen/auth_aws/lib/aws_assign_instance_profile.py
- Reassign the instance profile during teardown
- Requires an update to the `iam_auth_ec2_instance_profile` project variable
- Required driver config changes in https://github.com/mongodb/mongo-python-driver/pull/1218
- Successful [reassignment](https://evergreen.mongodb.com/task_log_raw/mongo_python_driver_aws_auth_test__platform~ubuntu_20.04_python_version~3.7_aws_auth_test_latest_patch_bda9e3a0bb533b6d0c6c5141feeecb77c4d31709_646761f057e85a09b6954eaf_23_05_19_11_48_14/3?type=T#L2567)
- I will open a drivers ticket to track making the required changes
> BUILD-17302 AWS EC2 credential retrieval 404s in Drivers CI

- .evergreen/auth_aws/aws_e2e_ec2.js
- .evergreen/auth_aws/aws_tester.py
- .evergreen/auth_aws/lib/aws_assign_instance_profile.py
Tested with both [`aws_tester`](https://spruce.mongodb.com/version/6477dfc71e2d1768666c4fbe/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) and [Legacy Shell](https://spruce.mongodb.com/version/6477e8131e2d1768666c6135/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
`IMPORTANT: Found machine already has instance profile, skipping the assignment`
> DRIVERS-2639 Fix handling of EC2 Instance Profile in EG Tests

- .evergreen/csfle/azurekms/create-vm.sh
Remove extra quotes on default value of `AZUREKMS_IDENTITY`
This is a follow up to https://github.com/mongodb-labs/drivers-evergreen-tools/pull/294/files#diff-6996a1a9561c8d80fe15eac2063b2da6f999f3f4b01a93d15090045366693c05R19 to resolves observed task failures creating the virtual machine. [Example](https://spruce.mongodb.com/task/mongo_c_driver_testazurekms_variant_testazurekms_task_fff643a3144fcce08b3163cbd6437949fe466061_23_05_31_19_23_49/logs?execution=1). Here is the error message with values redacted:
```
The client '<redacted>' with object id '<redacted>' has permission to perform action 'Microsoft.Compute/virtualMachines/write' on scope '<redacted>'; however, it does not have permission to perform action 'Microsoft.ManagedIdentity/userAssignedIdentities/assign/action' on the …
```
> remove extra single quotes

- .evergreen/download-mongodb.sh
curl's --retry-all-errors is not available on versions older than 7.71.0, and the older --retry option does not retry non-transient server errors such as 4xx and 5xx. By using the --fail option and manually checking the status code of the completed curl command, this fix ensures that the `curl_retry` function retries all failures up to three times.
> PYTHON-3721 Make retry more robust

- .evergreen/download-mongodb.sh
- Update 7.0 server download version to `7.0.0-rc3`
7.0.0-rc3 appears to be latest release: https://jira.mongodb.org/browse/STAR-3966.
There appears to be no published download for 7.0.0-rc0 with RHEL 8.3 s390x. This caused task failures in the C driver attempting to test server 7.0. [STAR-3822](https://jira.mongodb.org/browse/STAR-3822) suggests that `Enterprise RHEL 8.3 s390x` and `Enterprise RHEL 7.2 s390x variants` were not published for 7.0.0-rc0.  There are published downloads for 7.0.0-rc1, 7.0.0-rc2, and 7.0.0-rc3:
https://downloads.mongodb.com/linux/mongodb-linux-s390x-enterprise-rhel83-7.0.0-rc0.tgz results in HTTP 403.
https://downloads.mongodb.com/linux/mongodb-linux-s390x-enterprise-rhel83-7.0.0-rc3.tgz results in successful download.
> Update 7.0 server download version to `7.0.0-rc3`

- .evergreen/auth_oidc/azure/start-mongodb.sh
- .evergreen/auth_oidc/azure/test.py
Tested in a PyMongo patch build: https://spruce.mongodb.com/task/mongo_python_driver_testazureoidc_variant_oidc_auth_test_azure_latest_patch_1269c006da2ad9c35d812ff309ded7beebc50e81_648b1219e3c33133ea520ba3_23_06_15_13_28_59/logs?execution=0.
> DRIVERS-2416 Force MONGODB-OIDC to be enabled

- .evergreen/mongodl.py
The `mongodl.py` script currently prints an error message like:
```
ValueError: No download for "archive" was found for the requested version+target+architecture+edition
```
Make troubleshooting CI issues easier by printing the parameters used to try to find a download in the error message:
```
ValueError: No download was found for version="7.0.0-nope" target="ubuntu2204" arch="x86_64" edition="enterprise" component="archive"
```
> Improve the 'not found' error message printed by mongodl.py

- .evergreen/csfle/activate-kmstlsvenv.sh
- Use a fork of PyKMIP including the fix from https://github.com/OpenKMIP/PyKMIP/pull/700
Patch build: https://spruce.mongodb.com/version/6495bca40305b92f8b3a593f
> DRIVERS-2659 use fork of PyKMIP

- .evergreen/download-mongodb.sh
Adds download URLs for MongoDB 6.0 on Ubuntu 22.04 to unblock testing on that platform.
> Add MongoDB download URLs for Ubuntu 22.04

- .evergreen/start-orchestration.sh
The existing if/else branch for terminating a zombie mongo-orchestration is missing a branch to account for Red Hat. This PR proposes that addition to the code.
> Include rhel utilities in PID termination if/else branch

- .evergreen/download-mongodb.sh
Ubuntu 22 does not support server versions 5.0 and earlier, so we can't install the legacy shell there.
> PYTHON-3935 Skip legacy shell on Ubuntu 22

- .evergreen/auth_aws/setup_secrets.py
- .evergreen/auth_oidc/utils.py
Migrate the OIDC Secrets handling to use the new `setup_secrets.py` script.
Tested in https://spruce.mongodb.com/task/mongo_python_driver_oidc_auth_test__platform~rhel8_python_version~3.9_oidc_auth_test_latest_patch_f2867a9abf277e664b46d3d30dd380e6ae77c9d4_64ee990cc9ec4495336145c5_23_08_30_01_19_18/logs?execution=0.
> DRIVERS-2585 Migrate OIDC Secrets Handling

- .evergreen/auth_aws/activate-authawsvenv.sh
- .evergreen/auth_oidc/activate-authoidcvenv.sh
- .evergreen/auth_oidc/azure/run-test.sh
- .evergreen/csfle/activate-kmstlsvenv.sh
- .evergreen/find-python3.sh
- .evergreen/ocsp/activate-ocspvenv.sh
- .evergreen/run-load-balancer.sh
- .evergreen/serverless/create-instance.sh
- .evergreen/start-orchestration.sh
- .evergreen/venv-utils.sh
Make the EVG outputs quieter:
- Use `$(find_python3 2>/dev/null)` in more places
- Use `pip install -q` for quieter pip installs
- Avoid error when trying to shut down an HAProxy that was not running
- Remove legacy code in venv scripts supporting Windows 2016
> Make EVG outputs quieter

- .evergreen/auth_aws/activate-authawsvenv.sh
- .evergreen/auth_aws/setup_secrets.py
- .evergreen/auth_oidc/activate-authoidcvenv.sh
Instead of a traceback, they'll see something like:
```
ERROR: The SSO session associated with this profile has expired or is otherwise invalid. To refresh this SSO session run aws sso login with the corresponding profile.
```
> DRIVERS-2585 Make the Secrets Access errors more user friendly

- .evergreen/auth_aws/aws_tester.py
- .evergreen/auth_aws/lib/aws_handle_oidc_creds.py
- .evergreen/auth_oidc/oidc_get_tokens.py
- .evergreen/auth_oidc/oidc_get_tokens.sh
- .evergreen/auth_oidc/utils.py
Tested with https://github.com/mongodb/mongo-python-driver/pull/1365
> DRIVERS-2616 Fix path handling for Windows

- .evergreen/atlas/setup-atlas-cluster.sh
- .evergreen/atlas/setup-variables.sh
- .evergreen/atlas/teardown-atlas-cluster.sh
The setup and teardown atlas cluster scripts create unique clusters per-commit.  This can result in multiple CI tasks for the same commit attempting to create the same cluster.
This PR uses the `task_id` (a default evergreen expansion) to ensure that generated clusters are unique per-task.
Here's a patch from Node: https://spruce.mongodb.com/version/64f8955c3627e0397fdb50c0/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
Note that this patch is failing because of unrelated `npm` version issues (we're fixing this separately) but you can see the cluster successfully spins up and tears down.
> add unique function generation

- .evergreen/atlas/setup-atlas-cluster.sh
- .evergreen/atlas/setup-variables.sh
- .evergreen/atlas/teardown-atlas-cluster.sh
The previous changes to make cluster names unique did not actually produce unique cluster names.  each task id starts with the project name, so piping the task_id into `base64 | head -c 8` produces the same string for each evergreen project.
This PR does two things:
- The task id is now hashed to ensure that it is unique per-commit per-CI run per-driver
- the `execution` expansion is also included, to ensure function names are unique across restarts
patch in Node showing unique cluster names for both tasks that use these scripts in CI: https://spruce.mongodb.com/version/65035e55d6d80a62019a64bc/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> DRIVERS-2723: ensure atlas cluster names are unique

- .evergreen/config.yml
Cleans up EVG testing matrix for currently supported server versions and distros.
Full passing patch build [here](https://spruce.mongodb.com/version/651484e2d1fe074855e98a6d/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
> DRIVERS-2736 Update Drivers-Evergreen-Tools for Supported Build Hosts

- .evergreen/config.yml
They must be run on Ubuntu, since they rely on the `docker` binary.
> Fix handling of docker related builds

- .evergreen/run-orchestration.sh
- .evergreen/start-orchestration.sh
- action.yml
Partially reverts some changes made in https://github.com/mongodb-labs/drivers-evergreen-tools/pull/352 concerning Python 3 binary lookup (motivated by [a stray explicit call to `python`](https://github.com/mongodb-labs/drivers-evergreen-tools/commit/f825f86fae3e5eecfa5da05a510ec5962fc7de88#diff-5eb412fc2cdeb6fab58a38e622949bedbda012b8bcb61e5e6daec62e5168af87L101)) to address build failures on some EVG distros where neither `python` nor `python3` are available in default binary paths.
The `Using Python3 binary: $PYTHON` case added in https://github.com/mongodb-labs/drivers-evergreen-tools/pull/352 is preserved to avoid a redundant call to `find_python3` when `start-orchestration.sh` is invoked via `run-orchestration.sh` (which already called `find_python3`). This _might_ still break EVG …
> Address build failures due to Python 3 binary lookup

- .evergreen/find-python3.sh
- Skip Python version 3.12 when selecting Python
PR was tested by modifying the C driver config to test an Ubuntu 20.04 variant: 
- Before PR (failing): https://spruce.mongodb.com/version/651d7eaa32f4177fe5a3bdad
- After PR (passing): https://spruce.mongodb.com/version/651d8991850e6195dac11cfe.
Many C driver tasks use Ubuntu 18.04, which does not appear affected (Ubuntu 18.04 reports Python 3.11.4)
Test failures are reported by multiple driver teams starting the mock KMIP server. Example failures in [Node](https://parsley.mongodb.com/evergreen/mongo_node_driver_next_rhel8_no_auth_tests_test_4.2_server_noauth_33933ba119df7a50ae48517c374de83ea2d19abf_23_10_04_13_52_56/0/task?bookmarks=0,7989&shareLine=288) and [Java](https://spruce.mongodb.com/task/mongo_java_driver_tests_jdk8_unsecure__vers …
> DRIVERS-2743 skip Python 3.12

- .evergreen/auth_aws/aws_tester.py
We have two different task definitions, one for Ubuntu 20 (focal), and one for Ubuntu 22 (jammy).  This adds logic to automatically select the correct task definition based on the build host.
Tested with https://spruce.mongodb.com/version/654842e17742ae674dc5b911/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC and
https://spruce.mongodb.com/version/654842991e2d172f0294962d/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> DRIVERS-2747 Use appropriate ECS task for current Ubuntu version

- .evergreen/auth_aws/aws_tester.py
Testing in Python: https://spruce.mongodb.com/version/654964af0ae606025899bfb0/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> DRIVERS-2747 Handle backwards compat for ECS task definition

- .evergreen/auth_oidc/azure/create-and-setup-vm.sh
- .evergreen/auth_oidc/azure/handle_secrets.py
- .evergreen/auth_oidc/azure/start-mongodb.sh
- .evergreen/auth_oidc/azure/test.py
- .evergreen/auth_oidc/oidc_write_orchestration.py
- .evergreen/auth_oidc/setup_oidc.js
This infrastructure will be needed to support testing drivers with multiple clients on Azure.  I tested it locally by running `create_and_update_vm.sh` and ensuring that the self-test passes.
> DRIVERS-2416 Add support for a second Azure client

- .evergreen/download-mongodb.sh
This updates the patch versions for 7.0, 6.0, 5.0, and 4.4 to the latest releases.
> Update MongoDB versions

- .evergreen/auth_oidc/README.md
- .evergreen/auth_oidc/azure/README.md
- .evergreen/auth_oidc/azure/create-and-setup-vm.sh
- .evergreen/auth_oidc/azure/run-driver-test.sh
- .evergreen/auth_oidc/azure/test.py
- .evergreen/config.yml
- .evergreen/csfle/azurekms/create-vm.sh
- .evergreen/csfle/azurekms/remote-scripts/setup-azure-vm.sh
Tested with https://github.com/mongodb/mongo-python-driver/pull/1443 
`======================== 15 passed, 21 skipped in 3.69s ========================`
> DRIVERS-2416 Add docs and tests for azure oidc

- .evergreen/run-orchestration.sh
Restore `CRYPT_SHARED_LIB_PATH` to `mo-orchestration.yml`
https://github.com/mongodb-labs/drivers-evergreen-tools/pull/378 appears to cause task failures in the C++ driver project due to a missing `CRYPT_SHARED_LIB_PATH` environment variable. [Example](https://spruce.mongodb.com/task/cxx_driver_integration_ubuntu1804_4.2_single_compile_and_test_with_shared_libs_patch_86d4a2b25287a1f75c26cf3bdc9fb7bd0086f4a9_65809d8ea4cf470922eaee32_23_12_18_19_29_20/logs?execution=0):
```
[2023/12/18 14:35:10.819] .evergreen/test.sh: line 243: CRYPT_SHARED_LIB_PATH: parameter null or not set
```
The `mo-orchestration.yml` file is overwritten in `run-orchestration.sh`, removing the previously appended `CRYPT_SHARED_LIB_PATH`.
This PR has been tested with the C++ driver: …
> GODRIVER-3061 restore `CRYPT_SHARED_LIB_PATH` to `mo-orchestration.yml`

- .evergreen/auth_aws/setup_secrets.sh
- .evergreen/auth_oidc/azure/README.md
- .evergreen/auth_oidc/azure/handle_secrets.py
- .evergreen/auth_oidc/azure/test.py
- .evergreen/auth_oidc/oidc_get_tokens.sh
- .evergreen/auth_oidc/oidc_write_orchestration.py
- .evergreen/auth_oidc/setup_oidc.js
- Add only one managed identity to the VM
- Use the object id of the managed identity as the `username` instead of as an auth mechanism property
Tested with https://github.com/mongodb/mongo-python-driver/pull/1443
>  DRIVERS-2416 Azure OIDC updates

- .evergreen/auth_aws/README.md
- .evergreen/auth_aws/aws_setup.sh
- Run `assume-role` setup before `session-creds` test case.
- Run `regular` setup before `env-creds` test case.
- Update setup steps in README.
This PR was tested with Go driver: https://spruce.mongodb.com/version/65a163291e2d174ef9b4d3df and C driver: https://spruce.mongodb.com/version/65a167d0850e61bbdb91b2d6
`aws_setup.sh "session-creds"` expects `creds.json` to exist (via `jsonkey` [here](https://github.com/mongodb-labs/drivers-evergreen-tools/blob/b01493d57e6716cb6385afaa4dc06330e4f33e01/.evergreen/auth_aws/aws_setup.sh#L68)). However, `aws_setup.sh "session-creds"` does not run `aws_tester.py`.
I expect this is OK in the Go driver. The Go driver runs the AWS test cases in the same Evergreen task. I expect `aws_setup.sh "assume-role"` is run before `aws_setup.sh "session-creds"`.
The …
> CDRIVER-4512 run `aws_tester.py` for `session-creds` and `env-creds` test cases

- .evergreen/config.yml
- .evergreen/docker/README.md
- .evergreen/docker/ubuntu18.04/Dockerfile
- .evergreen/docker/ubuntu18.04/base-entrypoint.sh
- .evergreen/docker/ubuntu18.04/local-entrypoint.sh
- .evergreen/docker/ubuntu18.04/test-entrypoint.sh
- .gitignore
Add support for pre-4.4 servers in Docker.  Created to help implement [DRIVERS-1641](https://jira.mongodb.org/browse/DRIVERS-1641): pre-4.4 mongos writeConcernError does not determine retryability
> Add Docker support for pre-4.4 Servers

- .evergreen/serverless/README.md
Turns out it doesn't work with a dash :)
> minor: fix a typo in .evergreen/serverless/README.md

- .evergreen/download-mongodb.sh
This PR bumps the following server versions:
* 7.0.4 -> 7.0.5
* 6.0.12 -> 6.0.13
* 5.0.23 -> 5.0.24
* 4.4.26 -> 4.4.28
* 4.2.24 -> 4.2.25
In addition, this PR updates mongosh from 1.8.1 to 2.1.1, and changes the version identifier for the rapid release from 6.3.1 to 7.2.0 (we apparently never updated this for 7.1).
I've tested the changes in the PHP driver and they work fine, including installing the new major version of mongosh: https://spruce.mongodb.com/version/65b7733e1e2d17d86f6187fb/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> Bump mongosh and server versions

- .evergreen/aws_lambda/run-deployed-lambda-aws-tests.sh
The motivating use case here is Rust, which requires the `--beta-features` flag.
> DRIVERS-2384 Allow extra args to sam build

- .evergreen/atlas/README.md
- .evergreen/atlas/setup-atlas-cluster.sh
- .evergreen/atlas/setup-variables.sh
- .evergreen/atlas/teardown-atlas-cluster.sh
- .evergreen/aws_lambda/run-deployed-lambda-aws-tests.sh
- .evergreen/config.yml
- Enforce status code when creating cluster.
- Remove the need to pass in `execution` and `task_id` by storing the cluster name.
- Make Atlas standalone and not tied to Lambda, since it is used in other contexts.
- Make the Atlas base URI configurable so we can change it to non-prod.
- Add Atlas Test.
Tested with the Go Driver [here](https://spruce.mongodb.com/version/65e7dc5a562343a977ef45c6/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC).
> DRIVERS-2851 Fix Handling of Atlas Cluster Creation

- .evergreen/atlas/README.md
- .evergreen/atlas/setup-atlas-cluster.sh
- .evergreen/atlas/setup-secrets.sh
- .evergreen/atlas/setup.sh
- .evergreen/aws_lambda/README.md
- .evergreen/secrets_handling/README.md
Tested with Python driver [here](https://spruce.mongodb.com/version/6602be018a65e0000796feaf/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC).
> DRIVERS-2851 Use Cloud-Dev for Atlas Clusters

- .evergreen/github_app/assign-reviewer.mjs
Tested against https://github.com/mongodb/mongo-python-driver/pull/1545
```
node assign-reviewer.mjs -p /Users/steve.silvester/workspace/mongo-python-driver/.github/reviewers.txt -h 994c368f505a85012995a4ebc912d111a8852006 -o mongodb -n mongo-python-driver
Review already submitted!
+ popd
~/workspace/drivers-evergreen-tools/.evergreen/github_app
```
> PYTHON-4243  Handle Submitted Review in Auto Review Assignment Script

- .evergreen/csfle/azurekms/README.md
When updating the Node driver noticed we needed to set one more variable for the scripts. Checked the Python driver and it does it as well.
> docs: update azure kms readme

- .evergreen/atlas/atlas-utils.sh
- .evergreen/serverless/create-instance.sh
#433 removed up usage of `jq` in atlas-utils.sh, but in doing so introduced a small typo which led to an error when parsing the response. There was also an additional usage of `jq` left in setup-cluster.sh, which I removed with analogous code. I've tested these changes and can confirm that they fix PHP's serverless tests on Debian 11.
> Fix serverless cluster setup

- .evergreen/download-mongodb.sh
Bump RAPID version to match Serverless deployments, because currently we have failing tests with following error message:
`The configured mongocryptd version 7.2.0 doesn't match the server version 7.3.1.`
> Bump RAPID version to match Serverless deployment.

- .evergreen/atlas/atlas-utils.sh
- .evergreen/download-mongodb.sh
Tested with go driver: https://spruce.mongodb.com/version/662fd1fcea00a40007adee4f/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> Bump stable server versions

- .evergreen/find-python3.sh
We need to check for Python in another location for `macos-14` and `macos-14-arm64` distos.
Here is [example run](https://spruce.mongodb.com/task/dot_net_driver_tests_compression_macOS__version~6.0_os~macos_14_arm64_topology~standalone_auth~noauth_ssl~nossl_compressor~snappy_test_netstandard21_patch_9eb4dca262de9cc8facc9829b3893cdd1b1cd8d4_663e544fd0bf5b0007aa926c_24_05_10_17_07_43?execution=0&sortBy=STATUS&sortDir=ASC) of that distos.
> Add Python binary path for AWS Mac Fleet

- .evergreen/csfle/README.md
Turns out the test servers are [spun up](https://github.com/mongodb-labs/drivers-evergreen-tools/blob/master/.evergreen/csfle/start-servers.sh#L33) on 9000..9002, not 8000..8002 🙂
> minor: fix ports in README.md

- .evergreen/auth_oidc/azure/remote-scripts/run-self-test.sh
- .evergreen/auth_oidc/gcp/remote-scripts/run-self-test.sh
We use a different build backend now, so a direct invocation of setup.py doesn't work.
> Fix OIDC self-test

- .evergreen/secrets_handling/README.md
The `-c` option is necessary to ensure the vault name arg is passed to `setup-secrets.sh` and not `bash` itself. This was overlooked in https://github.com/mongodb-labs/drivers-evergreen-tools/pull/449.
> Use bash -c option to invoke command with its own args

- .evergreen/ocsp/mock-ocsp-responder-requirements.txt
The stable version of oscrypto has a [bug](https://github.com/wbond/oscrypto/issues/75) that prevents it from working with OpenSSL 3.0.10:
```
Traceback (most recent call last):
[2024/06/27 14:49:14.487]   File "/data/mci/91c84d5568444dead3a62ac8435331d4/drivers-tools/.evergreen/ocsp/ocsp_mock.py", line 13, in <module>
[2024/06/27 14:49:14.487]     import mock_ocsp_responder
[2024/06/27 14:49:14.487]   File "/data/mci/91c84d5568444dead3a62ac8435331d4/drivers-tools/.evergreen/ocsp/mock_ocsp_responder.py", line 56, in <module>
[2024/06/27 14:49:14.487]     from oscrypto import asymmetric
[2024/06/27 14:49:14.487]   File "/data/mci/91c84d5568444dead3a62ac8435331d4/drivers-tools/.evergreen/ocsp/ocspvenv/lib/python3.10/site-packages/oscrypto/asymmetric.py", line 19, in <module>
[2024/06/27 …
```
> Use newer version of oscrypto for OCSP mock server

- .evergreen/ensure-binary.sh
- .evergreen/handle-paths.sh
- .evergreen/ocsp/ecdsa/mock-delegate-revoked.sh
- .evergreen/ocsp/ecdsa/mock-delegate-valid.sh
- .evergreen/ocsp/ecdsa/mock-revoked.sh
- .evergreen/ocsp/ecdsa/mock-valid.sh
- .evergreen/ocsp/rsa/mock-delegate-revoked.sh
- .evergreen/ocsp/rsa/mock-delegate-valid.sh
- .evergreen/ocsp/rsa/mock-revoked.sh
- .evergreen/ocsp/rsa/mock-valid.sh
- .evergreen/run-orchestration.sh
- .evergreen/stop-orchestration.sh
Related to DRIVERS-2852
The GitHub Action does not explicitly use a shell when calling `run-orchestration.sh`, but instead relies on the shebang to choose the appropriate shell. This causes warnings when running the action:
```
/home/runner/work/drivers-evergreen-tools/drivers-evergreen-tools/.//.evergreen/run-orchestration.sh: 23: /home/runner/work/drivers-evergreen-tools/drivers-evergreen-tools/.//.evergreen/handle-paths.sh: [[: not found
/home/runner/work/drivers-evergreen-tools/drivers-evergreen-tools/.//.evergreen/run-orchestration.sh: 40: /home/runner/work/drivers-evergreen-tools/drivers-evergreen-tools/.//.evergreen/handle-paths.sh: [[: not found
/home/runner/work/drivers-evergreen-tools/drivers-evergreen-tools/.//.evergreen/run-orchestration.sh: 59: …
```
> Standardise bash shebang

- .evergreen/serverless/create-instance.sh
- .evergreen/serverless/download-crypt.sh
We currently download the rapid release for serverless, but this is prone to being outdated and needs manual updating. With this change, the serverless `create-instance` script attempts to download crypt_shared for the matching version. If this version is not available, the setup will fail, indicating there's a problem with the serverless version. Previously, you would sometimes get test failures (for example in CSFLE/QE tests) when versions don't match.
Tested with the PHP driver and confirmed that it downloads MongoDB 8.0 (our serverless instances are running 8.0.0-rc13).
> Download correct crypt_shared version when starting serverless instance

- .evergreen/run-orchestration.sh
Surprisingly, this works on most operating systems, but Debian 12 doesn't like it.
> Use correct python binary in run-orchestration

- .github/workflows/tests.yml
This adds testing on MacOS for the GitHub Action, ensuring that mongo-orchestration is able to start servers.
> Run action tests on MacOS

- .evergreen/docker/run-server.sh
To fix an observed error running `run-server.sh` with a Cygwin shell:
```
/root/base-entrypoint.sh: line 10: cd: /root/drivers-evergreen-tools/.evergreen:
No such file or directory
```
The error appears caused by the Unix-style path in the host path of the `-v` argument. This PR changes the host path to Windows-style.
Example before:
```
-v /cygdrive/c/code/drivers-evergreen-tools:/root/drivers-evergreen-tools
```
Example after:
```
-v C:\code\drivers-evergreen-tools:/root/drivers-evergreen-tools
```
https://docs.docker.com/reference/cli/docker/container/run/#volume notes:
> On Windows, you must specify the paths using Windows-style path semantics.
> fix `run-server.sh` volume path in Cygwin

- .evergreen/docker/run-server.sh
This reverts commit b0e2d57ece3d041313f8026edf0da2a6803aa6db.
To fix [failing GitHub actions tests](https://github.com/mongodb-labs/drivers-evergreen-tools/actions/runs/10254785646). I am not-yet sure what the cause of the failure is.
> Revert "fix `run-server.sh` volume path in Cygwin (#464)"

- .evergreen/github_app/README.md
- .evergreen/github_app/apply-labels.mjs
- .evergreen/github_app/apply-labels.sh
- .evergreen/github_app/assign-reviewer.mjs
- .evergreen/github_app/assign-reviewer.sh
- .evergreen/github_app/backport-pr.sh
- .evergreen/github_app/create_or_modify_comment.mjs
- .evergreen/github_app/create_or_modify_comment.sh
- .evergreen/github_app/get-access-token.sh
- .evergreen/github_app/get_backport_target.mjs
- .evergreen/github_app/setup-secrets.sh
- .evergreen/github_app/utils.mjs
- .evergreen/github_app/utils.sh
- .evergreen/install-node.sh
- .evergreen/secrets_handling/setup-secrets.sh
We won't have a way to test the new script in EVG until it is merged.  I verified that the script works when run manually locally.
> DRIVERS-2956 Add Script to Cherry-Pick PRs

- .evergreen/atlas/atlas-utils.sh
- .evergreen/auth_aws/activate-authawsvenv.sh
- .evergreen/auth_oidc/activate-authoidcvenv.sh
- .evergreen/csfle/activate-kmstlsvenv.sh
- .evergreen/docker/ubuntu18.04/Dockerfile
- .evergreen/docker/ubuntu20.04/Dockerfile
- .evergreen/download-mongodb.sh
- .evergreen/find-python3.sh
- .evergreen/handle-paths.sh
- .evergreen/ocsp/activate-ocspvenv.sh
- .evergreen/run-orchestration.sh
- .evergreen/serverless/create-instance.sh
- .evergreen/start-orchestration.sh
- .evergreen/stop-orchestration.sh
- .gitignore
- Makefile
- README.md
A redo of #473 based on feedback from @eramongodb 
- Allow PYTHON to be provided instead of using find_python3
- Fix handling of `pathlib.Path().expanduser()` on Windows
- Add convenience Makefile targets for `run-server` and `stop-server`
- Add top level documentation for running servers.
> Usability improvements (redux)

- .evergreen/github_app/utils.mjs
It is consumed as `const {comment, issue_number } = await findComment(octokit, owner, repo, targetSha, bodyMatch, "open");`, which was getting read in as an `undefined` `issue_number`.
>  DRIVERS-2956 Fix return value of findComment in Github App

- .evergreen/github_app/backport-pr.sh
- .evergreen/github_app/create_or_modify_comment.mjs
Tested against an actual PR this time.  😅
> GODRIVER-3314 Fix handling of failed cherry-pick

- .evergreen/config.yml
- .evergreen/docker/ubuntu18.04/Dockerfile
- .evergreen/docker/ubuntu18.04/base-entrypoint.sh
- .evergreen/docker/ubuntu18.04/test-entrypoint.sh
- .evergreen/docker/ubuntu20.04/Dockerfile
- .evergreen/docker/ubuntu20.04/base-entrypoint.sh
- .evergreen/docker/ubuntu20.04/test-entrypoint.sh
- .evergreen/handle-paths.sh
- Makefile
- Fix handling of `USERPROFILE` on Windows
- Add more robustness to `make clean`
- Use the Makefile in the docker containers for dogfooding
> More usability improvements for local server

- .evergreen/config.yml
- .evergreen/start-orchestration.sh
Passing build: https://spruce.mongodb.com/version/66d8ad0bd0d8e80007870224/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> Fix support for RHEL 7.0

- .evergreen/serverless/create-instance.sh
Without this fix, `download-crypt.sh` will write the expansion to `$SCRIPT_DIR/serverless-expansion.yml` rather than `$CURRENT_DIR/serverless-expansion.yml`.
> RUST-2024 Fix CRYPT_SHARED_LIB_PATH expansion

- .evergreen/download-mongodb.sh
Copies the pattern used in `run-orchestration.sh`.
> PYTHON-4734 Allow download-mongodb to run under sh

- .evergreen/retry-with-backoff.sh
Change function declaration syntax used to be compatible with sh.
> fix: make function syntax compatible with sh

- .evergreen/config.yml
- .evergreen/download-mongodb.sh
- .github/workflows/tests.yml
[DEVPROD-5083](https://jira.mongodb.org/browse/DEVPROD-5083)
[DEVPROD-40](https://jira.mongodb.org/browse/DEVPROD-40)
[DEVPROD-21](https://jira.mongodb.org/browse/DEVPROD-21)
> PYTHON-4764 Update to use current supported EVG hosts

- .evergreen/config.yml
- .evergreen/ensure-binary.sh
- .evergreen/install-rust.sh
- .gitignore
The Python team has a need for a Rust compiler on the hosts.
Copied from [rust driver](https://github.com/mongodb/mongo-rust-driver/blob/6a23464f6351a77ee97ff2cfbbc7fc196fd5a849/.evergreen/install-dependencies.sh).
Also adds test for our binary installers.
> Add a Rust Installer

- .evergreen/start-orchestration.sh
DRIVERS-2991 Properly kill old MO server to avoid "Address already in use" errors.
The ss+awk solution doesn't work on RHEL 8 anymore for unknown reasons:
```
$ ss -tlnp 'sport = :8889'
State                           Recv-Q                           Send-Q                                                       Local Address:Port                                                       Peer Address:Port
LISTEN                          0                                5                                                                127.0.0.1:8889                                                            0.0.0.0:*                               users:(("mongo-orchestra",pid=7676,fd=5))
$ ss -tlnp 'sport = :8889' | awk 'NR>1 {split($7,a,","); print a[1]}'
```
Perhaps `ss` was updated and reports …
> DRIVERS-2991 Properly kill old MO server to avoid "Address already in use" errors

- .evergreen/auth_oidc/gcp/setup.sh
- .evergreen/auth_oidc/setup.sh
Passing build of the go driver: https://spruce.mongodb.com/task/mongo_go_driver_testoidc_variant_oidc_auth_test_gcp_patch_60ded84e486dda6eea4f446d642571489a3ed3d0_66f220595dbfb3000702f953_24_09_24_02_13_56/logs?execution=0
> GODRIVER-3358 Add authSource override to OIDC connection strings

- .evergreen/start-orchestration.sh
Addresses the following possible error on certain distros (e.g. Ubuntu 18.04) due to `lsof` returning more than one PID:
```
start-orchestration.sh: line 76: kill: 4850
5401: arguments must be process or job IDs
```
Extends all find-and-kill-PID routines to support the possibility of multiple PIDs being returned by the PID query command.
> Support handling multiple PIDs in killport

- .evergreen/github_app/assign-reviewer.mjs
Assign PR reviewers in round-robin order instead of pseudo-random order. While pseud-random order guarantees evenness across lots of PRs, it can lack evenness in the short term, sometimes assigning too many PRs to one person.
> Assign Github PR reviews in round-robin order.

- .evergreen/k8s/configure-pod.sh
The GKE cluster takes a while to be ready for interaction.  This increases the backoff time.
```
[2024/10/02 06:38:06.927] + TIMEOUT=5
[2024/10/02 06:38:06.927] + ../retry-with-backoff.sh kubectl cp ./remote-scripts/setup-pod.sh test-gke-14252:/tmp/setup-pod.sh
[2024/10/02 06:38:06.929] Waiting for pod to be ready... done.
[2024/10/02 06:38:06.929] Configuring pod test-gke-14252...
[2024/10/02 06:38:06.929] retry_with_backoff: running 'kubectl cp ./remote-scripts/setup-pod.sh test-gke-14252:/tmp/setup-pod.sh' - attempt n. 1 ...
[2024/10/02 06:38:08.594] E1002 11:38:08.594792   76783 v2.go:167] "Unhandled Error" err="next reader: read tcp 10.128.250.152:36480->34.86.146.245:443: read: connection reset by peer"
[2024/10/02 06:38:08.594] E1002 11:38:08.594804   76783 v2.go:129] "Unhandled …
```
> Use a longer timeout for k8s configuration

- .evergreen/auth_oidc/azure/run-driver-test.sh
- .evergreen/csfle/azurekms/copy-file.sh
- .evergreen/csfle/azurekms/create-vm.sh
- .evergreen/csfle/azurekms/run-command.sh
- .evergreen/csfle/azurekms/set-ssh-ip.sh
Restrict access to Azure VMs. Resolves DRIVERS-2987.
Tested CSFLE with C driver: https://spruce.mongodb.com/version/66fc4490ce827200070347f9
Tested CSFLE+OIDC with Go driver: https://spruce.mongodb.com/patch/66fc50fb3bc93e0007ef36a2
[azure vm create](https://learn.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest#az-vm-create-optional-parameters) documents:
> Defaults to open ports for allowing RDP on Windows and allowing SSH on Linux.
Though the private SSH key is expected to be secured, this PR disables the default open port to follow recommendations noted in DRIVERS-2987.
Every script that may `ssh` to the Azure VM sets the IP of the network security group. I expect the setup script (`create-and-setup-vm.sh`) may run on a different Evergreen host scripts used to test …
> DRIVERS-2987 Restrict access to Azure VMs

- .evergreen/download-mongodb.sh
Failing build: https://spruce.mongodb.com/task/mongo_python_driver_prev_rel_tests_python_version_rhel8_compression__platform~rhel8_compression~snappy_python_version~3.12_c_extensions~with_c_extensions_test_5.0_standalone_ce5395085c175f344b94cdbeccb48466822c75c7_24_10_02_16_20_37/logs?execution=4
> Revert change to 5.0 download version

- .evergreen/auth_aws/aws_tester.py
https://spruce.mongodb.com/version/66fecd7b33b96200077dfef2/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
PyMongo now imports asyncio, and we were previously not sending environment variables to subprocesses. Those variables are needed to load system dlls in Python.
> GODRIVER-3371 Fix aws auth on windows

- .evergreen/run-orchestration.sh
- .gitignore
This prevents us from modifying the orchestration files in place that use ABSOLUTE_PATH_REPLACEMENT_TOKEN.
Tested with the C driver: https://spruce.mongodb.com/version/67041e9b7f1bfe000734ae39/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> DRIVERS-2999 Use isolated orchestration file

- .evergreen/ocsp/README.md
- .evergreen/ocsp/ocsp_mock.py
- .evergreen/ocsp/setup.sh
- .evergreen/ocsp/teardown.sh
Tested with the python driver: https://spruce.mongodb.com/version/66febce8ff87620007764ac6/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
Part of the ongoing effort to move more logic out of our evergreen config.  😄
> PYTHON-4818 Add OCSP Helper Scripts

- .evergreen/download-mongodb.sh
This PR adds the 4.2 server archive link to the Debian 10 distro.
The C driver is [looking](https://github.com/mongodb/mongo-c-driver/pull/1760#discussion_r1797140094) to test the 4.2 server against a supported Linux Evergreen environment since Ubuntu 18.04 is dropped from [support](https://jira.mongodb.org/browse/DRIVERS-2592). Debian 10 is still [supported](https://wiki.corp.mongodb.com/pages/viewpage.action?pageId=116563465) by Evergreen and [works](https://docs.google.com/spreadsheets/d/1-sZKW70HbVt2yHOWa18qwBwi-gBcn54tWmronnn89kI/edit?gid=0#gid=0) with a 4.2 server.
The 4.2 server archive was not included underneath the `linux-debian-10` distro in `download-mongodb.sh`. See [this](https://spruce.mongodb.com/task/mongo_c_driver_cse_matrix_openssl_cse_sasl_cyrus_openssl_debian10_gcc_tes …
> Add MongoDB 4.2 server archive to Debian 10

- .evergreen/config.yml
- .evergreen/download-mongodb.sh
- .evergreen/find-python3.sh
- .evergreen/mongodl.py
This is the first step in DRIVERS-3002.  
This PR adds the following capabilities for parity with download-mongodb.sh:
- Handle named versions (8.0, etc)
- Handle "rapid" version
- Add support for perf versions
- Normalize the handling of rhel downloads
- Add option to just print the url 
- Add option to download the debug version of a server
The next PR will create a mongosh-dl.py to handle finding the mongosh download link.
The final PR will use mongodl.py and mongosh-dl.py directly in download-mongodb.sh.
> DRIVERS-3002 Add download-mongodb capabilities to mongodl

- .evergreen/config.yml
- .evergreen/download-mongodb.sh
WARNING: strict unmarshalling YAML: load project error(s): error unmarshalling yaml strict: yaml: unmarshal errors:
line 1114: field teardown_group_can_fail_task not found in type model.parserTaskGroup
WARNING: task group 'serverless_task_group' has a teardown task timeout of 1800 seconds, which exceeds the maximum of 180 seconds
> Address warnings in evergreen config

- .evergreen/auth_oidc/k8s/README.md
- .evergreen/config.yml
- .evergreen/ensure-binary.sh
- .evergreen/k8s/eks/README.md
AKS local testing is not yet set up, but that isn't a strict requirement for DRIVERS-2882.   I'll follow up with that fix next week.
> DRIVERS-2882 Update EKS documentation and test against AKS

- .evergreen/auth_oidc/azure/create-and-setup-vm.sh
https://learn.microsoft.com/en-us/cli/azure/azure-cli-sp-tutorial-7?tabs=bash#reset-credentials-returning-output-to-the-console-and-log-file
After being prompted by Azure:
```
ERROR: AADSTS7000222: The provided client secret keys for app 'xxx' are expired. Visit the Azure portal to create new keys for your app: https://aka.ms/NewClientSecret, or consider using certificate credentials for added security: https://aka.ms/certCreds.
```
> DRIVERS-2415 Use a certfile for Azure OIDC login

- .evergreen/csfle/kms_http_server.py
Intended to address observed errors in C# tests: "KMS response parser error with status 200, error: 'Unexpected: exceeded content length" seemingly caused by multiple HTTP responses returned on the same socket side-by-side.
> add missing return to mock KMS server

- .evergreen/csfle/kms_failpoint_server.py
Added `end_headers()`, otherwise the response is never sent.
> Fixed sending of mock http error in kms_failpoint_server.py

- .evergreen/csfle/kms_failpoint_server.py
- .evergreen/csfle/kms_http_common.py
Verified in C# and Python: https://spruce.mongodb.com/version/6750be2084e65a00077a3df7/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC.
Python failures are legitimate and will need to be handled in follow up tickets.
Matches the settings used with the old `ssl.wrap_socket()` API.
> DRIVERS-2743 Clean up TLS settings

- .evergreen/k8s/remote-scripts/setup-pod.sh
Pre-instal curl on the k8s pods to let C# Driver's script to pull and install dotnet SDK.
> Install curl in pod for k8s testing

- .evergreen/install-node.sh
Fixes https://spruce.mongodb.com/task/drivers_tools_tests_all__os_fully_featured~rhel8_auth~auth_ssl~nossl_test_install_binaries_9236d1edcae6350ac172a40d37a9d3a22932a7a1_24_12_05_22_07_26?execution=1&sortBy=STATUS&sortDir=ASC
```
[2024/12/18 16:54:43.916] + [[ -d /data/mci/e96ca0ab301bbc80047176335aacac90/drivers-tools/.evergreen/node-artifacts/nodejs/node-v18.20.5-linux-x64 ]]
[2024/12/18 16:54:43.916] + /data/mci/e96ca0ab301bbc80047176335aacac90/drivers-tools/.evergreen/retry-with-backoff.sh curl --fail --compressed --location --retry 8 --silent --show-error --max-time 900 https://nodejs.org/dist/v18.20.5/node-v18.20.5-linux-x64.tar.gz --output /data/mci/e96ca0ab301bbc80047176335aacac90/drivers-tools/.evergreen/node-artifacts/node-v18.20.5-linux-x64.tar.gz
[2024/12/18 16:54:43.917] …
```
> Use node 20 as the default LTS version

- .github/workflows/tests.yml
"Ubuntu-latest workflows will use Ubuntu-24.04 image" - https://github.com/actions/runner-images/issues/10636
> Use supported server version on ubuntu 24.04

- .evergreen/download-mongodb.sh
- .evergreen/mongodl.py
- .evergreen/mongosh_dl.py
As part of the effort to migrate to a python CLI for orchestration, move crypt_shared handling logic in `mongodl.py` and improve the default values of `mongodl.py` and `mongosh_dl.py`.  Allow both files to be called as libraries, so they can be used from the new orchestration cli.
> DRIVERS-3032 Improve usability of mongodl

- .evergreen/mongodl.py
- .evergreen/mongosh_dl.py
Allows finer-grained control of output, including CLI options for quiet and verbose.
> DRIVERS-3032 Use loggers in CLIs

- .evergreen/mongodl.py
[TUNE-74 ](https://jira.mongodb.org/browse/TUNE-74) Change full.json to cloud.json to support testing MongoDB 8.x on Amazon Linux 2.
> TUNE-74: source MongoDB versions from cloud.json to support 8.x binaries on AL2

- .evergreen/docker/README.md
Rancher desktop's `27.4.1-rd` does not do a great job of selecting the best architecture for an image, rather defaulting to the machine's architecture. This causes strange behavior, especially for dependencies that are specific to amd64 (libsnmp35, for example). Add section noting this to the docker README.md.
> Add section concerning amd64 with rancher desktop

- .evergreen/install-node.sh
Move's Node's npm version fallback into drivers tools for reuse.
Example CI run in Node against this branch: https://spruce.mongodb.com/task/mongo_node_driver_next_rhel80_large_Node20_test_4.0_replica_set_patch_13ca440500b515e9aaf0aef4409503c518d13413_67850d4b11594900069dd02e_25_01_13_12_55_40/logs?execution=0
> chore(NODE-6636): set proper npm version on node install

- .evergreen/config.yml
- .evergreen/csfle/README.md
- .evergreen/csfle/start-servers.sh
I tested this with the Go driver, which had use the background approach.  This will allow us to move the encryption setup to a task in the Python driver, without having to use the background approach.
> Properly daemonize the csfle servers

- .evergreen/process-utils.sh
The versions of `kill` on the platforms we commonly use (Ubuntu, RHEL, macOS) expect the `-SIGKILL` flag to come before the PID arguments.
```bash
$ kill "1234567890" -SIGKILL
-bash: kill: (1234567890) - No such process
-bash: kill: -SIGKILL: arguments must be process or job IDs
```
With `-SIGKILL` first:
```bash
$ kill -SIGKILL "1234567890"
-bash: kill: (1234567890) - No such process
```
```bash
$ kill "1234567890" -SIGKILL
-bash: kill: (1234567890) - No such process
-bash: kill: -SIGKILL: arguments must be process or job IDs
```
With `-SIGKILL` first:
```bash
$ kill -SIGKILL "1234567890"
-bash: kill: (1234567890) - No such process
```
```bash
❯ kill "1234567890" -SIGKILL
kill: kill 1234567890 failed: no such process
kill: illegal pid: -SIGKILL
```
With `-SIGKILL` first:
```bash
❯ kill …
```
> Fix order of 'kill' arguments in killport function.

- .evergreen/auth_aws/lib/ecs_hosted_test.sh
- .evergreen/install-cli.sh
- .evergreen/install-node.sh
- .evergreen/tests/test-cli.sh
- .evergreen/tests/test-csfle.sh
Prefer to avoid using `xtrace`, which propagates to the calling script when using `.` or `source`, resulting in a log leakage risk and unintended verbosity.
> Remove usages of xtrace

- .evergreen/install-cli.sh
- .evergreen/orchestration/drivers_orchestration.py
The PyMongo 4.11 release dropped support for MongoDB 3.6, so we need to install an older version of PyMongo when testing against 3.6.
> Fix support for MongoDB 3.6

- .evergreen/orchestration/drivers_orchestration.py
Tested with  PyMongo: https://spruce.mongodb.com/task/mongo_python_driver_encryption_win64_python3.9_test_latest_replica_set_noauth_ssl_sync_async_patch_34ae214e33e922e3478388517a2b37aa4fd64dba_679adc8acbcb43000725faf6_25_01_30_01_58_19/logs?execution=0
> DRIVERS-3032 Fix location of crypt_shared

- .evergreen/auth_aws/lib/container_tester.py
Passing run in Node: https://spruce.mongodb.com/version/679ceb0c3093610007dbc090/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> fix(DRIVERS-3086): use new ssh keys for AWS ecs tests

- .evergreen/orchestration/drivers_orchestration.py
Adds sensible defaults for version (latest) and topology (server) when en passed as env vars not cli args.
This was causing failures in csharp driver.
> Added sensible defaults in drivers_orchestration when env variables used

- .evergreen/install-cli.sh
Followup to https://github.com/mongodb-labs/drivers-evergreen-tools/pull/591 and https://github.com/mongodb-labs/drivers-evergreen-tools/pull/591.
Several issues appear to be related to the errors that motivated prior PRs:
- If `venv` already exists, it may be activated without a call to `pip install uv` even if `uv` has not yet been installed into that venv.
- uv may not necessarily be installed directly into `venv/bin` or `venv/Script`. It is possible for the binary to reside in a deeper subdirectory such as "site-packages", which in turn may also be within a Python-versioned subdirectory, such as "python-3.12" (given uv is designed to support multiple Python versions). The `pushd $1` after activating the virtual environment may additionally break `$PATH` expectations (although I would …
> DRIVERS-3032 ensure uv is installed after venv activation

- .evergreen/orchestration/drivers_orchestration.py
Here's an example mo-expansion.yml file:
```
CRYPT_SHARED_LIB_PATH: "/Users/bailey.pearson/dev/drivers-evergreen-tools/mongo_crypt_v1.dylib"
MONGODB_URI: mongodb://bob:pwd123@localhost:27017/?authSource=admin
```
notice that CRYPT_SHARED_LIB_PATH has its value in quotes, whereas MONGODB_URI does not.
This PR adds quotes around MONGODB_URI for consistency.
> fix: use consistent quoting in expansion file

- .evergreen/init-node-and-npm-env.sh
This won't actually guarantee 3.12 plus but it will get us a lot closer.
> fix: node-gyp requires 3.12+ python version

- .evergreen/k8s/gke/setup.sh
Gradle builds in Java driver were failing due to insufficient ephemeral storage, causing out-of-memory issues. This change increases the storage allocation to prevent eviction of the pod.
> Increase ephemeral storage size to prevent Gradle execution failures.

- .evergreen/mongodl.py
- .evergreen/tests/test-cli.sh
Fix `latest-build` download URL in mongodl for RHEL
Trying to download `latest-build` in mongodl for some RHEL distros results in error:
```
python ./.evergreen/mongodl.py  --version latest-build --target rhel9 --component archive
```
Comparing the URL in download-mongodb.sh on [before migrating to mongodl.py](https://github.com/mongodb-labs/drivers-evergreen-tools/blob/9142b7055ea5940e59ad41c4b069376f867031da/.evergreen/download-mongodb.sh#L151):
```
Old:     https://downloads.10gen.com/linux/mongodb-linux-x86_64-enterprise-rhel93${DEBUG}-latest.tgz
Current: https://downloads.10gen.com/linux/mongodb-linux-x86_64-enterprise-rhel9-latest.tgz
```
I expect some `latest-build` RHEL URLs include the minor version (`93` instead of `9`). To fix: this PR checks the URL in `latest` for a minor …
> Fix `latest-build` URL for RHEL

- .evergreen/orchestration/drivers_orchestration.py
This was lost in translation between bash and python.
> DRIVERS-3099 Show mongod --version

- .evergreen/mongodl.py
Reverts mongodb-labs/drivers-evergreen-tools#574 to fix failing downloads for rapid and latest binaries, due to releases being in cloud.json but not full.json.
I'll make the file name configurable next week.
> Revert "TUNE-74: source MongoDB versions from cloud.json to support 8.x binaries on AL2"

- .evergreen/orchestration/drivers_orchestration.py
- .evergreen/run-orchestration.sh
- README.md
Tested with https://github.com/mongodb/mongo-python-driver/pull/2159 using the new flags, 
and with the Go driver using just this branch: https://spruce.mongodb.com/version/67be4ed44371980007ea1060/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> DRIVERS-3119 Add options to provide certificate and CA files

- .github/workflows/tests.yml
"The Ubuntu 20.04 runner image will be fully unsupported by April 1, 2025"
> PYTHON-5131 Migrate off of Ubuntu 20.04 GitHub Actions Runners

- .evergreen/auth_aws/teardown.sh
- .evergreen/clean.sh
- .evergreen/mongodl.py
- .evergreen/orchestration/drivers_orchestration.py
- .evergreen/tests/test-cli.sh
- .github/workflows/tests.yml
- Makefile
Usability improvements for `run-orchestration.sh` - files should have the right permissions and be cleaned up properly between runs.
Tested with Go driver: https://spruce.mongodb.com/version/67c092578d250f0007a0c5ec/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
And C driver: https://spruce.mongodb.com/version/67c096758d250f0007a0e4c6/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> DRIVERS-3119 Enhanced cleanup and file permissions handling

- .evergreen/orchestration/drivers_orchestration.py
Passing build: https://spruce.mongodb.com/version/67c608cf377bba00074ad62e/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> PYTHON-5182 Fix handling of certificate path replacement

- .evergreen/auth_oidc/k8s/README.md
Copy-pasting the current examples results in invalid Evergreen configs because some keys have the wrong indentation, creating child objects rather than sibling keys.
> Fix indentation in Evergreen yaml examples for k8s OIDC setup.

- .evergreen/auth_aws/aws_setup.sh
- .evergreen/auth_aws/aws_tester.py
- .evergreen/auth_aws/lib/aws_assign_instance_profile.py
- .evergreen/orchestration/drivers_orchestration.py
- .evergreen/run-orchestration.sh
- .gitignore
Redo of #619, this time tested with the C dirver: https://spruce.mongodb.com/version/67c774d6bf14fd0007a5b681/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
The problem was that we weren't exporting USER, PASS, and SESSION_TOKEN anymore.
> PYTHON-5157 Convert aws tests to use python scripts

- .evergreen/config.yml
- .evergreen/csfle/azurekms/delete_old_azure_resources.py
- .evergreen/csfle/azurekms/delete_old_azure_resources.sh
Add a task to periodically delete leftover Azure resources from OIDC and KMS tasks.
Alerts were recently triggered due to leftover Azure resources created for testing.
Evergreen task groups for Azure clean-up resources in [teardown](https://github.com/mongodb/mongo-rust-driver/blob/2b35455e90217e04b6d85c2799d5bb741c428b5b/.evergreen/config.yml#L472-L483). However, this appears unreliable. For example, [this Rust OIDC task](https://spruce.mongodb.com/task/mongo*rust_driver_oidc_linux_oidc_auth_test_azure_latest_patch_2b35455e90217e04b6d85c2799d5bb741c428b5b_67bd0047e6df5c0007ab8f84_25_02_24_23_27*06/logs?execution=0) logs:
```
<2025/02/24 18:29:43.330> Heartbeat received signal to abort task.
```
I expect the task was aborted before storing the VM name as an expansion:
``` …
```
> DRIVERS-3117 periodically remove old Azure resources

- .evergreen/config.yml
- .evergreen/ocsp/mock-ocsp-responder-requirements.txt
- .evergreen/ocsp/ocsp_mock.py
- .evergreen/ocsp/setup.sh
- .evergreen/ocsp/teardown.sh
- .evergreen/tests/test-ocsp.sh
Tested with https://github.com/mongodb/mongo-python-driver/pull/2190: https://spruce.mongodb.com/version/67cc94d4b26dff000739c152/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
and the C driver: https://spruce.mongodb.com/version/67ced2d64d80c40007a73649/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
Uses `waitress` to create a production flask server that can be run as a daemon on all platforms.
Adds tests for OCSP server on Mac, Windows, and RHEL.
> PYTHON-5195 Allow OCSP server to be run as a daemon

- .evergreen/auth_aws/aws_tester.py
Related to #622
The Java drivers aws assume role test started failing. It turns out that as `&` has special meaning in the shell the `MONGODB_URI` needed to be quoted, so it can be exported.
Patch: https://spruce.mongodb.com/version/67cee1a70374ea0007bcf0d1/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> JAVA-5811: Quote MONGODB_URI variable.

- .evergreen/ocsp/mock-ocsp-responder-requirements.txt
This was previously added in https://github.com/mongodb-labs/drivers-evergreen-tools/pull/452 but inadvertently reverted in https://github.com/mongodb-labs/drivers-evergreen-tools/pull/626
> User newer oscrypto to fix detection of later OpenSSL versions

- .evergreen/auth_oidc/azure/remote-scripts/run-self-test.sh
Passing build: https://spruce.mongodb.com/task/mongo_python_driver_auth_oidc_ubuntu_22_test_auth_oidc_azure_patch_a548f7a3d45f8827e88e8f2c060ffb1045e5883e_67d1d4965ed4c20007970cf8_25_03_12_18_38_24/logs?execution=0&sortBy=STATUS&sortDir=ASC
> PYTHON-5196 Use consistent secrets file name in oidc tests

- .evergreen/install-cli.sh
- .evergreen/run-orchestration.sh
- .evergreen/setup.sh
Set `UV_PYTHON` to ensure proper handling of python version used by uv.
Python build: https://spruce.mongodb.com/version/67df43c9d002970007b1e750/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
C driver build: https://spruce.mongodb.com/version/67e16af4593ae00007d7bc52/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
Python build for Amazon2 tests: https://spruce.mongodb.com/version/67e175f5d6d198000775282e/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC (4.0 failures are expected, I should have only scheduled 4.2-7.0).
Failing build: https://spruce.mongodb.com/task/mongo_python_driver_test_amazon2_python3.10_test_4.0_replica_set_noauth_ssl_sync_async_patch_1145c9de543bb5748a61dbf338385ff2ff6330c6_67e02ff8212e8700072c416d_25_03_23_16_00_10?execution=0&sortBy=STATUS&sortDir=ASC
Traceback:
``` …
```
> DRIVERS-3032 Fix handling of python used by UV

- .evergreen/auth_oidc/teardown.sh
Passing build in PyMongo: https://spruce.mongodb.com/version/67e2eeab7f515f00071ef695/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
MacOS: 
```
[2025/03/25 13:13:53.003] Deleting Atlas Cluster...
[2025/03/25 13:13:53.003] {}
[2025/03/25 13:13:53.003] Deleting Atlas Cluster... done.
```
Windows:
```
[2025/03/25 13:13:10.078] Deleting Atlas Cluster...
[2025/03/25 13:13:10.078] {}
[2025/03/25 13:13:10.078] Deleting Atlas Cluster... done.
```
Ubuntu:
```
[2025/03/25 13:01:25.925] No teardown required!
```
> DRIVERS-3141 Fix handling of OIDC teardown on Linux hosts

- .evergreen/atlas/README.md
- .evergreen/atlas/atlas-utils.sh
- .evergreen/atlas/setup-secrets.sh
- .evergreen/aws_lambda/README.md
- .evergreen/secrets_handling/README.md
Passing build: https://spruce.mongodb.com/version/67e55a9f4f2ca00007d66b63/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
"Using Atlas base url: https://cloud-qa.mongodb.com/api/atlas/v1.0"
This does not affect serverless builds, which still use `atlas-dev`:
"Using Atlas base url: https://account-dev.mongodb.com/api/atlas/v1.0"
> DRIVERS-3111 Use atlas-qa by default

- .evergreen/config.yml
- .evergreen/docker/teardown.sh
Addresses the error seen during teardown: `unknown shorthand flag: 'a' in -a`.
> DRIVERS-3055 Fix docker teardown

- .evergreen/mongosh_dl.py
https://mongodb.slack.com/archives/CUHC9R8J0/p1744138986132869
https://spruce.mongodb.com/task/mongo_node_driver_next_macos_14_arm64_test_rapid_server_46cb56def4cc3b87c8430af24b73aeb8386f9ea0_25_04_08_16_20_47/logs?execution=0&sortBy=STATUS&sortDir=ASC
A perhaps super transient problem, mongosh temporarily had a 2.5.0 release before needing to reset to fix an issue with the release process. Our CI task was lucky enough to fetch that version number as latest but find no corresponding zip to download. We suspect this could be avoided if we also filtered for draft releases but I'm not sure if that information would be included in the response so I check for the presence of the key first.
https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#list-releases
> Information about …
> filter out mongosh draft releases when determining latest

- .evergreen/orchestration/drivers_orchestration.py
I tested this several times with https://spruce.mongodb.com/version/68406b88ac869900072382a4/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC and it works as expected.
The OIDC failure is unrelated, I'm opening a separate PR.
> INTPYTHON-641 Always prefer podman over docker

- .evergreen/config.yml
- .evergreen/serverless/README.md
Full removal is deferred to [DRIVERS-3203](https://jira.mongodb.org/browse/DRIVERS-3203).
> DRIVERS-3202 Remove Serverless testing

- .evergreen/config.yml
Patch build: https://spruce.mongodb.com/version/6840ee95c1b5aa000723f40c/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
The serverless failure can be ignored, I'm removing serverless testing as part of [DRIVERS-3202](https://jira.mongodb.org/browse/DRIVERS-3202) in a follow up PR.
> DRIVERS-3188 Remove reliance on Evergreen instance profile credentials for remaining tasks

- .evergreen/docker/run-server.sh
- .evergreen/docker/ubuntu20.04/Dockerfile
Tested locally:
```bash
$ bash run-server.sh
~/workspace/drivers-evergreen-tools ~/workspace/drivers-evergreen-tools/.evergreen/docker
[+] Building 7.7s (7/10)                                                                           docker:desktop-linux
=> [internal] load build definition from Dockerfile                                                               0.0s
=> => transferring dockerfile: 1.04kB                                                                             0.0s
=> [internal] load metadata for docker.io/library/ubuntu:20.04                                                    1.0s
...
```
```bash
$ CI=1 bash run-server.sh
~/workspace/drivers-evergreen-tools/.evergreen/docker ~/workspace/drivers-evergreen-tools/.evergreen/docker
Traceback (most recent call last): …
```
> DRIVERS-3208 Option to avoid docker login for local testing

- .evergreen/docker/login.py
This addresses failures seen in [ai-ml-pipeline-testing](https://spruce.mongodb.com/task/ai_ml_pipeline_testing_test_pymongo_voyageai_rhel_test_pymongo_voyageai_local_patch_573242238993df7988c446ccf4fc4f95161b15ef_686413f704006c0007a9ab5d_25_07_01_16_59_36/logs?execution=1) due to mixing docker and podman:
```
[2025/07/01 12:10:48.150] Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
...
[2025/07/01 12:10:48.150] DEBUG    Using command: 'sudo /usr/bin/podman run --rm -d --name mongodb_atlas_local -p 27017:27017 --health-cmd '/usr/local/bin/runner healthcheck' -P 901841024863.dkr.ecr.us-east-1.amazonaws.com/dockerhub/mongodb/mongodb-atlas-local:latest'
[2025/07/01 12:10:48.225] Trying to pull 901841024863.dkr.ecr.us-east-1.amazonaws.com/dockerhub/mongodb/mongod …
```
> INTPYTHON-641 Fix docker login to prefer podman

- .evergreen/csfle/azurekms/delete_old_azure_resources.sh
Follow-up to https://github.com/mongodb-labs/drivers-evergreen-tools/pull/666 to fix the `delete_old_azure_resources` task ([example](https://spruce.mongodb.com/task/drivers_tools_delete_old_azure_resources_delete_old_azure_resources_688568825d4e6b00074ba745_25_07_26_23_45_06/logs?execution=0)):
```
line 24: pythom: command not found
```
Verified with this [patch build](https://spruce.mongodb.com/version/688a62c401270600072a9727) (includes a temporary change to make the task patchable).
> Fix Azure resource deletion

- .evergreen/csfle/azurekms/remote-scripts/setup-azure-vm.sh
Remove `bullseye-backports` to fix observed failures with Azure VMs:
```
E: The repository 'http://debian-archive.trafficmanager.net/debian bullseye-backports Release' does not have a Release file.
```
Fixes `test-oidc-azure`: https://spruce.mongodb.com/version/688d03d7dc00fb0007683d9f
Fixes the C driver task `testazurekms-task`: https://spruce.mongodb.com/version/688d0079f2350700075c8071
This is a known issue on the Azure VM image. See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1109866.
On an Azure VM created with `debian-11:11:0.20221020.1174`, `/etc/apt/sources.list` contains:
```
deb http://debian-archive.trafficmanager.net/debian bullseye main
deb-src http://debian-archive.trafficmanager.net/debian bullseye main
deb http://debian-archive.trafficmanager.net/debian-security …
```
> DRIVERS-3238 Fix Azure VM source list

- .evergreen/install-cli.sh
Resolves DRIVERS-3249. Extends the changes made in https://github.com/mongodb-labs/drivers-evergreen-tools/pull/585 (to restore pymongo compatibility with MongoDB Server 3.6) to accomodate the recent pymongo 4.14 release, which dropped support for MongoDB Server 4.0 in https://github.com/mongodb/mongo-python-driver/pull/2353.
> DRIVERS-3249 fix pymongo compat with server version 4.0 and older

- .evergreen/auth_oidc/start_local_server.sh
To fix an observed error when running `start_local_server.sh` with `AWS_PROFILE` exported:
```bash
export AWS_PROFILE        
.evergreen/auth_oidc/start_local_server.sh
```
Results in:
```
unknown shorthand flag: 'v' in -v
```
> move `-v` flag from `docker build` to `docker run`

- .evergreen/auth_oidc/gcp/teardown.sh
- .evergreen/auth_oidc/k8s/setup.sh
Testing with https://spruce.mongodb.com/version/68de7f4418e7c300072048d3/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
GKE test failure is unrelated, the cluster was torn down properly.
> DRIVERS-3302 Fix OIDC Atlas Teardown
